### PR TITLE
Remove unsed method and call

### PR DESCRIPTION
**Pull request by Pectojin**
As discussed in #3579

Seems to still compile and run fine. No visible issue from this change in my testing.

### CODE REVIEW

**Comment by warwickmm** [comment]
I tested various operations (backup, compact, repair, restore, test) and everything appeared to work normally.  Can anyone (@kenkendk?) comment on what the `BuildLookupTable` does and why it isn't needed anymore?

**Comment by kenkendk** [comment]
> Can anyone (@kenkendk?) comment on what the BuildLookupTable does and why it isn't needed anymore?

The code will build a lookup table for paths, such that queries checking if the file has changed can _potentially_ be done faster. Unfortunately, building the table also takes a bit of time, so the overall savings were never really great.

The code is only activated if `--disable-filepath-cache=false` is set. I don't think anyone has reported significant speedups from this, so we can remove it but we should set the option to be deprecated such that users having it toggled on gets a warning (add an extra string argument with a message saying is not longer doing anything):
https://github.com/duplicati/duplicati/blob/master/Duplicati/Library/Main/Options.cs#L514

And this should be removed as well:
https://github.com/duplicati/duplicati/blob/master/Duplicati/Library/Main/Options.cs#L1578-L1589

**Comment by Pectojin** [comment]
I've removed the toggle method and, I think, set the flag as deprecated.

**Comment by Pectojin** [comment]
Missed one reference to the deleted method.

**Comment by kenkendk** [comment]
Great work!

**Pull request merged**
