### PR TITLE
Store fileset in a temp file instead of a memory stream

### PR DESCRIPTION
**Pull request by tygill**
I've been running Duplicati on a Raspberry Pi 4 4GB for a few weeks now, and have seen a number of OutOfMemoryExceptions which I'm trying to figure out how best to prevent.

Several of these exceptions have been in FilesetVolumeWriter.AddFilelistFile(), which is called when the fileset volume is disposed / closed. In looking at that method, I noticed that the temporary stream containing the JSON encoded fileset is stored in a memory stream. This change adds a flag `--cache-fileset-on-disk` which instead uses a temp file to store this temporary data before it is copied to the compressed file. The default is still to use the memory stream.

Callstacks for the exceptions I've seen:

```
System.OutOfMemoryException: Insufficient memory to continue the execution of the program.
  at (wrapper alloc) System.Object.AllocVector(intptr,intptr)
  at System.Buffers.TlsOverPerCoreLockedStacksArrayPool`1[T].Rent (System.Int32 minimumLength) [0x0009d] in <254335e8c4aa42e3923a8ba0d5ce8650>:0 
  at System.IO.Stream.InternalCopyTo (System.IO.Stream destination, System.Int32 bufferSize) [0x00005] in <254335e8c4aa42e3923a8ba0d5ce8650>:0 
  at System.IO.Stream.CopyTo (System.IO.Stream destination) [0x00084] in <254335e8c4aa42e3923a8ba0d5ce8650>:0 
  at (wrapper remoting-invoke-with-check) System.IO.Stream.CopyTo(System.IO.Stream)
  at Duplicati.Library.Main.Volumes.FilesetVolumeWriter.AddFilelistFile () [0x00047] in <24ac72dcd8164f1d99ab1cdfaa4d4619>:0 
  at Duplicati.Library.Main.Volumes.FilesetVolumeWriter.Close () [0x00008] in <24ac72dcd8164f1d99ab1cdfaa4d4619>:0 
  at Duplicati.Library.Main.Volumes.FilesetVolumeWriter.Dispose () [0x00000] in <24ac72dcd8164f1d99ab1cdfaa4d4619>:0 
  at Duplicati.Library.Main.Operation.BackupHandler.RunAsync (System.String[] sources, Duplicati.Library.Utility.IFilter filter, System.Threading.CancellationToken token) [0x01033] in <24ac72dcd8164f1d99ab1cdfaa4d4619>:0 
  at CoCoL.ChannelExtensions.WaitForTaskOrThrow (System.Threading.Tasks.Task task) [0x00050] in <9a758ff4db6c48d6b3d4d0e5c2adf6d1>:0 
  at Duplicati.Library.Main.Operation.BackupHandler.Run (System.String[] sources, Duplicati.Library.Utility.IFilter filter, System.Threading.CancellationToken token) [0x00009] in <24ac72dcd8164f1d99ab1cdfaa4d4619>:0 
  at Duplicati.Library.Main.Controller+<>c__DisplayClass14_0.<Backup>b__0 (Duplicati.Library.Main.BackupResults result) [0x0004b] in <24ac72dcd8164f1d99ab1cdfaa4d4619>:0 
  at Duplicati.Library.Main.Controller.RunAction[T] (T result, System.String[]& paths, Duplicati.Library.Utility.IFilter& filter, System.Action`1[T] method) [0x0026f] in <24ac72dcd8164f1d99ab1cdfaa4d4619>:0 
  at Duplicati.Library.Main.Controller.Backup (System.String[] inputsources, Duplicati.Library.Utility.IFilter filter) [0x00074] in <24ac72dcd8164f1d99ab1cdfaa4d4619>:0 
  at Duplicati.Server.Runner.Run (Duplicati.Server.Runner+IRunnerData data, System.Boolean fromQueue) [0x00353] in <d12ca99c5557481d973bd260fb77853b>:0 
```

```
System.OutOfMemoryException: Insufficient memory to continue the execution of the program.
  at (wrapper alloc) System.Object.AllocVector(intptr,intptr)
  at SharpCompress.Compressors.Deflate.DeflateManager.Initialize (SharpCompress.Compressors.Deflate.ZlibCodec codec, SharpCompress.Compressors.Deflate.CompressionLevel level, System.Int32 windowBits, System.Int32 memLevel, SharpCompress.Compressors.Deflate.CompressionStrategy strategy) [0x000b7] in <5717dfb1db2745ffb30a27e1fee78b19>:0 
  at SharpCompress.Compressors.Deflate.DeflateManager.Initialize (SharpCompress.Compressors.Deflate.ZlibCodec codec, SharpCompress.Compressors.Deflate.CompressionLevel level, System.Int32 bits, SharpCompress.Compressors.Deflate.CompressionStrategy compressionStrategy) [0x00000] in <5717dfb1db2745ffb30a27e1fee78b19>:0 
  at SharpCompress.Compressors.Deflate.ZlibCodec._InternalInitializeDeflate (System.Boolean wantRfc1950Header) [0x0002a] in <5717dfb1db2745ffb30a27e1fee78b19>:0 
  at SharpCompress.Compressors.Deflate.ZlibCodec.InitializeDeflate (SharpCompress.Compressors.Deflate.CompressionLevel level, System.Boolean wantRfc1950Header) [0x00007] in <5717dfb1db2745ffb30a27e1fee78b19>:0 
  at SharpCompress.Compressors.Deflate.ZlibBaseStream.get_z () [0x0004a] in <5717dfb1db2745ffb30a27e1fee78b19>:0 
  at SharpCompress.Compressors.Deflate.ZlibBaseStream.end () [0x00000] in <5717dfb1db2745ffb30a27e1fee78b19>:0 
  at SharpCompress.Compressors.Deflate.ZlibBaseStream.Dispose (System.Boolean disposing) [0x0002c] in <5717dfb1db2745ffb30a27e1fee78b19>:0 
  at System.IO.Stream.Close () [0x00000] in <254335e8c4aa42e3923a8ba0d5ce8650>:0 
  at System.IO.Stream.Dispose () [0x00000] in <254335e8c4aa42e3923a8ba0d5ce8650>:0 
  at (wrapper remoting-invoke-with-check) System.IO.Stream.Dispose()
  at SharpCompress.Compressors.Deflate.DeflateStream.Dispose (System.Boolean disposing) [0x00015] in <5717dfb1db2745ffb30a27e1fee78b19>:0 
  at System.IO.Stream.Close () [0x00000] in <254335e8c4aa42e3923a8ba0d5ce8650>:0 
  at System.IO.Stream.Dispose () [0x00000] in <254335e8c4aa42e3923a8ba0d5ce8650>:0 
  at (wrapper remoting-invoke-with-check) System.IO.Stream.Dispose()
  at SharpCompress.Writers.Zip.ZipWriter+ZipWritingStream.Dispose (System.Boolean disposing) [0x0001d] in <5717dfb1db2745ffb30a27e1fee78b19>:0 
  at System.IO.Stream.Close () [0x00000] in <254335e8c4aa42e3923a8ba0d5ce8650>:0 
  at System.IO.Stream.Dispose () [0x00000] in <254335e8c4aa42e3923a8ba0d5ce8650>:0 
  at Duplicati.Library.Main.Volumes.FilesetVolumeWriter.AddFilelistFile () [0x0005e] in <24ac72dcd8164f1d99ab1cdfaa4d4619>:0 
  at Duplicati.Library.Main.Volumes.FilesetVolumeWriter.Close () [0x00008] in <24ac72dcd8164f1d99ab1cdfaa4d4619>:0 
  at Duplicati.Library.Main.Volumes.FilesetVolumeWriter.Dispose () [0x00000] in <24ac72dcd8164f1d99ab1cdfaa4d4619>:0 
  at Duplicati.Library.Main.Operation.BackupHandler.RunAsync (System.String[] sources, Duplicati.Library.Utility.IFilter filter, System.Threading.CancellationToken token) [0x01033] in <24ac72dcd8164f1d99ab1cdfaa4d4619>:0 
  at CoCoL.ChannelExtensions.WaitForTaskOrThrow (System.Threading.Tasks.Task task) [0x00050] in <9a758ff4db6c48d6b3d4d0e5c2adf6d1>:0 
  at Duplicati.Library.Main.Operation.BackupHandler.Run (System.String[] sources, Duplicati.Library.Utility.IFilter filter, System.Threading.CancellationToken token) [0x00009] in <24ac72dcd8164f1d99ab1cdfaa4d4619>:0 
  at Duplicati.Library.Main.Controller+<>c__DisplayClass14_0.<Backup>b__0 (Duplicati.Library.Main.BackupResults result) [0x0004b] in <24ac72dcd8164f1d99ab1cdfaa4d4619>:0 
  at Duplicati.Library.Main.Controller.RunAction[T] (T result, System.String[]& paths, Duplicati.Library.Utility.IFilter& filter, System.Action`1[T] method) [0x0026f] in <24ac72dcd8164f1d99ab1cdfaa4d4619>:0 
  at Duplicati.Library.Main.Controller.Backup (System.String[] inputsources, Duplicati.Library.Utility.IFilter filter) [0x00074] in <24ac72dcd8164f1d99ab1cdfaa4d4619>:0 
  at Duplicati.Server.Runner.Run (Duplicati.Server.Runner+IRunnerData data, System.Boolean fromQueue) [0x00353] in <d12ca99c5557481d973bd260fb77853b>:0 
```

### CODE REVIEW

**Comment by warwickmm** [comment]
Thanks @tygill.  I was a little worried about this when we made the change to store this in memory.  In fact, can you think of a reason why we shouldn't always store this on disk?  That was the behavior before the [fix](https://github.com/duplicati/duplicati/commit/e0899a2a91aab8e982e9674461c0504907ef5845#diff-bd7255b05b4f39949e263b1e06d63901) for adding the "control-files" to the dlist file was made.

**Comment by tygill** [comment]
Seeing that original code seems to confirm my suspicions. I assume a zip or other compressed file doesn't support having multiple files open at once? I had also wondered if the fact that the fileset (which is a big json blob) was taking a lot of memory because it wasn't being compressed when stored this way.

I don't see any downsides to always using a temp file (except for the fact that if the system has enough memory, memory would likely be faster than disk).

One catch is that this temp file isn't compressed either, though that's probably not too big a concern when writing to the disk.

**Comment by warwickmm** [comment]
I think that always using a temp file might be the best approach.  I imagine that moving the temporary fileset back to disk doesn't significantly increase Duplicati's footprint in the temp folder (relative to the block files).

Just curious, how large are the fileset files in your case?

**Comment by tygill** [comment]
It looks like in another backup of mine (not the one that is crashing, but one that should be at least the same number of files) the compressed dlist files are no bigger than 10mb. So even if the uncompressed files are 5-10x bigger than that, it shouldn't be too much extra on disk.

**Comment by tygill** [comment]
I just pushed a change to remove the setting and make the temp file the only behavior.

**Comment by warwickmm** [comment]
Looks good to me.  Thanks @tygill.

**Pull request merged**
