### PR TITLE
Fix useless notification "Warning: Got 0 warning(s)"

### PR DESCRIPTION
**Pull request by mikaelmello**
When a restore was made in which 0 files were restored, the Result has Success set to "Warning" and then a notification displaying "Warning: Got 0 warning(s)" appears

Another solution to avoid this was to remove the condition to return "Warning" when 0 files were restored but this could affect things that I don't know about and the problem actually belongs to the notification, so I've decided to simply show warning notifications if and only if we actually have notifications or warnings.

I don't know if this is the behavior wanted by you, just thought it would be a nice PR.

### CODE REVIEW

**Comment by kenkendk** [comment]
I would like to know why the `ParsedResult` is set to `warning` if there are zero warnings.
Do you know why?

Other than that I agree, showing "Warning: 0 warnings" is pretty useless :).

**Comment by kenkendk** [comment]
Ok, I see the problem now. The restore operation has a check to see if zero files are restored, but this does not create any warning messages (as I would expect).

I suggest we change it, so the controller emits a message if zero files are changed (around line 470 in `RestoreHandler.cs`):
```csharp
if (m_result.FilesRestored == 0 && m_result.ParsedResult == ParsedResultType.Success)
    Logging.Log.WriteWarningMessage(LOGTAG, "NoFilesRestored", null, "Restore completed without errors, but no files were restored");
```

Then we can remove the extra logic in the Restore result class, so it becomes:
```csharp
public override ParsedResultType ParsedResult
{
    get
    {
        if (Errors != null && Errors.Any())
            return ParsedResultType.Error;
        else if (Warnings != null && Warnings.Any())
            return ParsedResultType.Warning;
        else
            return ParsedResultType.Success;
    }
}
```
I prefer this approach as just not popping up the warning message hides the fact that something unexpected has happened.

**Comment by mikaelmello** [comment]
I think this is better too. Will do it tomorrow.

A suggestion: the current UI to see errors or warnings directly related to backups is so lacking. You have to click on show, then click the item of the last operation to open the _entire_ log and manually search for the Errors and Warnings fields.

Over the next week I'll take a look into that too

**Comment by kenkendk** [comment]
> A suggestion: the current UI to see errors or warnings directly related to backups is so lacking.

I agree. When I made it, there were many other things (there still is), so it was a matter of just getting something that works. The current solution is just dumping the log table into the browser tab, and it could be soooo much better.

For starters, we should tag each backup run with a unique ID, and write that into the log table, so we can group messages into what run it belongs to. This will make it much more user friendly, when it displays a list of operations.

We should also record the log ID for each message, such that the notification can point to the actual message, insted of just opening the log page.

There is a mention of this idea here: https://forum.duplicati.com/t/suggestion-to-improve-queue-and-notifications/3067

I recall there was a more detailed suggestion somewhere that included a design with status icons next to each entry, but I cannot find it.

**Comment by mikaelmello** [comment]
Which log `id` and `message` do you recommend me to use?

**Comment by mikaelmello** [comment]
Done. I'll also map a reasonable amount of strings to `Strings.cs` so they can be i18n'd.

**Comment by kenkendk** [comment]
Arh, I just started a canary build, so this will go in the next build.

> Edit: LacunaSoftware@e97310b Can I follow with these changes?

Sure.

**Comment by mikaelmello** [comment]
> A suggestion: the current UI to see errors or warnings directly related to backups is so lacking. You have to click on show, then click the item of the last operation to open the entire log and manually search for the Errors and Warnings fields.

Following up on this, what do you think of `PrintSerializeObject()` writing JSON? With that change I guess it would be way easier to parse the LogData messages and display them nicely on the Web UI.

**Comment by kenkendk** [comment]
> Following up on this, what do you think of PrintSerializeObject() writing JSON? With that change I guess it would be way easier to parse the LogData messages and display them nicely on the Web UI.

Fine by me. We can also introduce something that has a more UI specific layout. I think the raw `PrintSerializeObject()` includes the log lines, which can be quite a lot of data to transfer, even locally.

**Comment by mikaelmello** [comment]
I did a quick test with the following changes:
image

In a backup with 2000 files it does not seem to get big. I guess only Logs above Warning are stored.

https://pastebin.com/rUVeE1dM

**Comment by kenkendk** [comment]
There is the "collectionlimit" which sets how many of each list are included before an ellipsis is added, so maybe we can just use that (set it to `0`), and then get the error/warning messages via a direct call if the user expands the UI element where they are displayed?

**Comment by mikaelmello** [comment]
I'll move the posts to a proper issue and continue from there

**Pull request merged**
