### PR TITLE
Removed code for supporting .NET < 4.8

### PR DESCRIPTION
**Pull request by kenkendk**
Defensive code for not supporting TLS1.3 removed

### CODE REVIEW

**Comment by ts678** [comment]
What happens if the OS doesn't support TLS 1.3?

**Comment by ts678** [comment]
[Protocols in TLS/SSL (Schannel SSP)](https://learn.microsoft.com/en-us/windows/win32/secauthn/protocols-in-tls-ssl--schannel-ssp-) says Windows 10 has TLS 1.3 as "Not Supported" for client or server.
I'd just like to make sure that Duplicati still lands nicely at TLS 1.2 on any systems that don't support 1.3.
I don't know the answer, so I thought I'd ask.

**Comment by kenkendk** [comment]
I had not considered that any recent systems would lack this, so thanks for pointing it out. 

I think I will set it to "system default" which is what MS recommends. This should pick whatever is best, given the system.

**Comment by ts678** [comment]
[SslProtocols Enum](https://learn.microsoft.com/de-de/dotnet/api/system.security.authentication.sslprotocols?view=net-8.0) suggests `None` rather than `Default` (which has an outdated meaning). I don't know which you meant.

**Comment by ts678** [comment]
The MS recommended None (poor choice of words by MS) verssus SystemDefault (deprecated or forbidden) came up again.

I'm not looking at FluentFTP, but I thought I'd report what 2.0.8.1 and 2.0.9.101 (looks like change is in 2.0.9.100) say in UI.

2.0.8.1

```
C:\Duplicati\duplicati-2.0.8.1_beta_2024-05-07>Duplicati.CommandLine.exe help allowed-ssl-versions
  --allowed-ssl-versions (Flags): Sets allowed SSL versions
    This option changes the default SSL versions allowed. This is an advanced
    option and should only be used if you want to enhance security or work
    around an issue with a particular SSL protocol.
    * values: Ssl3, Tls, Tls11, Tls12, SystemDefault, Tls13
    * default value: SystemDefault
```

> --allowed-ssl-versions=Tls12,SystemDefault,Tls13

image

2.0.9.101

```
C:\Duplicati\duplicati-2.0.9.101_canary_2024-06-27-win-x64-gui>Duplicati.CommandLine.exe help allowed-ssl-versions
  --allowed-ssl-versions (Flags): Sets allowed SSL versions
    This option changes the default SSL versions allowed. This is an advanced option and should only be used if you want to enhance security or work around an issue with a particular SSL protocol.
    * values: SystemDefault, Ssl3, Tls, Tls11, Tls12, Tls13
    * default value: SystemDefault
```

> --allowed-ssl-versions=SystemDefault

image

[Changes to Kestrel's default supported TLS protocol versions #418](https://github.com/dotnet/aspnetcore/issues/22563) announced Kestrel's 2020 move to [SslProtocols.None](https://docs.microsoft.com/en-us/dotnet/api/system.security.authentication.sslprotocols), and the Duplicati move to SystemDefault concerns me. Would you like me to test more (including Wireshark) to see what it's negotiating?

**Pull request merged**
