### PR TITLE
minor UI improvements for file picker

### PR DESCRIPTION
**Pull request by msilvers**
a few minor UI improvements for file picker.
- disabled selecting multiple folders for backup or restore destinations; multiselect is only allowed when selecting data files
- added checkboxes with tri-state support to show which files are and are not included. 

These issues are mentioned on issue #1404 

filemultiselect
filesingleselect

### CODE REVIEW

**Comment by kenkendk** [comment]
Nice!

There seems to be missing some handling of the multiselect in the `select_node` and in `browsePath` callback method? Currently it only returns a single node, but with multiselect it should return a list?

**Comment by msilvers** [comment]
Yes...I think the current UI allows multi select (via Ctrl+Click) but has the same issue.  (seems like the same behavior as reported in issue #1067?)
Either way...I'm working on a fix for that and will submit it soon.

**Comment by kenkendk** [comment]
OK.

I am working on a new UI based on Angular, which already supports filters and multi-select for source folders:
https://github.com/duplicati/duplicati/tree/angular_ui/Duplicati/Server/webroot/ngax

It will not be the default UI right away though, there are many loose ends that needs fixin.

**Comment by kenkendk** [comment]
I merged your changes, if you get the multiselect fixed, you can either do it here or in a new PR.
If you would like credit for the changes, could you please add yourself to the "acknowledgements.txt" file and send a new PR?
https://github.com/duplicati/duplicati/blob/master/Duplicati/License/acknowledgements.txt

**Pull request merged**
