### PR TITLE
Upload files in chunks to prevent timeouts on large files

### PR DESCRIPTION
**Pull request by ReneHezser**
Used example from https://msdn.microsoft.com/en-us/library/office/dn904536.aspx to prevent timeouts on uploading the backup to OneDrive for Business.

### CODE REVIEW

**Comment by FootStark** [comment]
Thanks for the solution. I didn't check it with larger block-files, and wasn't aware of possible timeouts. Do you know the timeout values for SharePoint and can specify with which file sizes the timeouts happen? I will review, test and merge the code on the weekend.

**Comment by ReneHezser** [comment]
Hi Stefan,
I can't tell you about the specific size for files that cause timeouts. My backup is several GB and it didn't upload to OneDrive for Business (SharePoint Online). With the changes, I was able to upload a 5.x GB file.
René

**Comment by ReneHezser** [comment]
Any chance the pull request will be accepted? The current implementation doesn't let me perform successful uploads to OneDrive for Business in SharePoint Online.

**Comment by renestach** [comment]
Just one hint: The "max backup files size" has been set to 50MB for some reasons. You can increase this to 100MB or 200MB but everything above is not recommended. 

Why did you choose to have single files of 5GB?

**Comment by ReneHezser** [comment]
I didn't. At least not that I know. I've configured the backup through the web interface of duplicati.

**Comment by renestach** [comment]
What value does the "max backup file size" on step 4 of your backup have? Default value is 50MB and then no uploaded file should be larger than 50MB.

**Comment by FootStark** [comment]
I am at it. I have to change something to allow non seekable streams. Should be done today/tomorrow.

**Comment by FootStark** [comment]
BTW: It would still be great to know what exactly causes your timeouts and where they occur. Maybe it's related to another environment condition; I still couldn't reproduce the timeout. MS states [timeout to be 30 min here](https://msdn.microsoft.com/en-us/library/office/dn904536.aspx), so that would be an awefully slow internet connection not transferring 50MB/30min...

**Comment by ReneHezser** [comment]
@FootStark With the default settings the files are 50MB and not timeout occured

**Comment by FootStark** [comment]
Will be merged with added control-options via #1771.

**Pull request closed without merging**
