### PR TITLE
Fix negative bytes to go issue

### PR DESCRIPTION
**Pull request by drwtsn32x**
Under certain circumstances the bytes to go will be shown as negative:

dbc696f948ba515d252bb040ff869eb6a16e6bde

This seems to happen most notably when backing up a large file that is a significant portion of the total backup set size.  It is easiest to reproduce if you create a new backup set and choose a single large file to back up.

After some testing it appears the root cause is that `m_filesizeprocessed` is incremented when the file is done being processed, but some time may pass before `m_curfileoffset` is set back to zero.  If the status bar updates during this brief time window, the size of the file is counted twice when the `sizeleft` value is calucated in `AppUtils.js`:

`var sizeleft = $scope.state.lastPgEvent.TotalFileSize - $scope.state.lastPgEvent.ProcessedFileSize - $scope.state.lastPgEvent.CurrentFileoffset;`

This can result in `sizeleft` being a negative number if, as stated above, the file being counted twice is a significant portion (over 50%) of the total backup set size.   Even if it is not significant, it still results in an incorrect calculation.

My proposed solution is to immediately set `m_curfileoffset` to zero when `UpdatefilesProcessed` is called in `ProgressHandler.cs:72`.

In my testing it seems to work well.

### CODE REVIEW

**Comment by Pectojin** [comment]
Won't it cause issues if we set m_curfileoffset to zero both immediately and later?

**Comment by BlueBlock** [comment]
> Won't it cause issues if we set m_curfileoffset to zero both immediately and later?

When tested it I saw the bytes go to 0 while on the last file. Not a big issue but not really accurate. This maybe part of it but I also saw that folders are being included in the 'file' count.

Try it with maybe 5 files and have 4 or 5 directories to see the result.

Directories should probably not be included in the count.

**Comment by drwtsn32x** [comment]
> When I had tested it I saw the bytes go to 0 while on the last file.

What do you mean, the bytes to go said zero?  Isn't that correct when the last file has finished?

Regarding the file count - this change should have no bearing on that.

**Comment by drwtsn32x** [comment]
> Won't it cause issues if we set m_curfileoffset to zero both immediately and later?

I don't see how it would cause an issue, but it does seem unnecessary to set it to zero both at the end of a file and at the start of the next file.  I could do testing where we remove the set to zero at the start of a file, if you wish.

**Comment by Pectojin** [comment]
I guess it wouldn't cause an issue to set it to 0 twice. But it's a bit confusing.

I'd prefer it cleaner with only setting it once.

**Comment by BlueBlock** [comment]
> > When I had tested it I saw the bytes go to 0 while on the last file.
> 
> What do you mean, the bytes to go said zero? Isn't that correct when the last file has finished?
> 
> Regarding the file count - this change should have no bearing on that.

From an end-user perspective I would not expect a file in-progress to reduce the bytes remaining. 0 to me says it is done.

**Comment by drwtsn32x** [comment]
> I'd prefer it cleaner with only setting it once.

Ok, I will do some testing. It should work if we only set it to zero at file completion.

**Comment by drwtsn32x** [comment]
> From an end-user perspective I would not expect a file in-progress to reduce the bytes remaining. 0 to me says it is done.

That's exactly right. This change sets "current file processed" to zero right at file completion, when the "total bytes processed" is incremented by that that file's size.  The file is done at that point.

**Comment by drwtsn32x** [comment]
@Pectojin - ok I did testing where OperationProgressUpdater.StartFile() does NOT set m_curfileoffset = 0.  It works as expected ... there is no effective change, we just aren't setting it to zero twice between files any more.

For the very first file, m_curfileoffset is already zero since this object is newly initialized. For subsequent files, it is set to zero by OperationProgressUpdater.UpdatefilesProcessed() - which is called when a file is complete. 

I will update the pull request shortly....

**Comment by Pectojin** [comment]
Ok, that looks more clean even if I guess it doesn't have an effect in practice.

**Comment by drwtsn32x** [comment]
> When I had tested it I saw the bytes go to 0 while on the last file.

@BlueBlock - did you mean the per-file progress meter? I just noticed this myself.  The last file, once complete, shows 0% on its individual progress bar.

The main progress bar is corrected with this fix but messes up the individual file progress meter. Not sure of a clean way to fix this correctly without introducing another variable.  Will think on it some more...

**Comment by drwtsn32x** [comment]
Screen shot showing the new problem - main status bar is correct, but individual file status bar drops back to 0% when complete (and is last file):

Capture

One solution I can think of is to create a new variable that indicates the current file is complete.  In the javascript portion we change the calculation to NOT include "currentFileOffset" in the main progress meter when that flag is true, because at that point the ProcessedFileSize has been incremented.

When the next file starts, that flag is set back to false.

Thoughts?

**Comment by drwtsn32x** [comment]
Suggested fix in PR https://github.com/duplicati/duplicati/pull/3904

It rolls back the changes made by this PR and implements a newer solution....

**Pull request merged**
