### PR TITLE
Added french canadian language

### PR DESCRIPTION
**Pull request by flafleur**
Added french canadian language and tried to get updated other languages

### CODE REVIEW

**Comment by Pectojin** [comment]
@kenkendk can you confirm if this looks right? I'm not entirely sure how the language integration works.

**Comment by Pectojin** [comment]
@flafleur it seems like you've accidentally updated this pull request by pushing an unrelated commit to your master branch. 

I'd recommend splitting your changes out into branches so new development doesn't affect currently open pull requests :)

**Comment by flafleur** [comment]
@Pectojin,  first experience git.  I hope all is correct now.

**Comment by Pectojin** [comment]
@flafleur we all started some time :)

It looks like the commit is on it's own branch now but still also on the master branch here. 

I'd suggest either rolling back one commit on the master branch or alternatively making a new branch for this change and then closing this pull request and making a new one from the new branch.

It's possible to roll back one commit by using `git reset --hard commit-sha` and then force pushing back on master with `git push origin master --force`, but you should be careful force pushing as you can potentially delete data on your repo unintentionally.

You can test the behavior of the reset command on a test branch first just to see what it looks like on github
```
# git checkout -b test
# git reset --hard 5cbd7900fc36c1f29bc6b815ee21746ef62683af
# git push origin test
```
Then if everything looks good on the test branch you can do  the same on the master :)

**Comment by flafleur** [comment]
I create a new one #3709

**Comment by Pectojin** [comment]
Thanks :)

**Pull request closed without merging**
