### PR TITLE
Root unix filesystem as a source path

### PR DESCRIPTION
**Pull request by mach-o**
I believe these changes should fix the problems with unix root filesystems identified in [issue #1532](https://github.com/duplicati/duplicati/issues/1532). I essentially largely eliminated the recurring DIR_SEP variable and substituted its use with calls to System.IO.Path.GetFullPath.

I also renamed a LICENSE.txt file to license.txt because it caused compile problems on linux due to case sensitivity. Since a number of files reference it as lower case, I thought it easiest to make one single change, but if you prefer to keep the capital filename, you could sort through the references.

### CODE REVIEW

**Comment by mach-o** [comment]
I'm having some cold feet about this, excludes aren't working properly for me. For example: `backup $target / --exclude=/sys` still tries to backup the tree below /sys.

Not sure whether this is a result of these changes or an unrelated problem.

**Comment by kenkendk** [comment]
Great work!

For the UpdateVersionStamp tool, I don't think there needs to be any fixes. It is only used to set the version number, so it should not be used on `/` at all.

The license renaming is fine.

If you remove the TODO line in UpdateVersionStamp I will merge it.

**Comment by mach-o** [comment]
Thanks! I've removed the line. Please check whether --exclude works for you after (and perhaps also before) merging.

**Comment by kenkendk** [comment]
Your update comment got lost in the stream :)

What should be the issue with --exclude? This only affects the OS specific calls?

**Comment by mach-o** [comment]
I now suspect that the exclude issue is completely unrelated, and is the one already being tracked in [issue 1039](https://github.com/duplicati/duplicati/issues/1039). Is it possible that --exclude simply isn't implemented at all? If so, a warning should appear to the user whenever a user uses the flag that it's being ignored until it's fixed.

**Comment by mach-o** [comment]
Or is Issue 1039 only referring to the form --exclude=*.mp3 rather than --exclude=/boot ?

In any case, neither option currently works for me, but in any case I don't think it has anything to do with this patch.

**Comment by kenkendk** [comment]
I would be surprised if it was related to this patch.
Issue #1039 is just that --exclude gives a warning, not that it does not work. I will close it.
If you need to exclude a folder, you need to specify the path with a trailing slash:
`--exclude=/boot/`

This is slightly confusing as many other tools allow you to use either format, but the format allows you to exclude all files called boot with `--exclude=*/boot` or all folders with `--exclude=*/boot/` at the expense of having to write `--exclude=[.*/boot/?]` to exclude both types.

**Comment by steilerDev** [comment]
@kenkendk Maybe unrelated, but whats your process on getting new versions out? Saying when will this feature be shipped to clients?

**Comment by mach-o** [comment]
kenkendk: Unless I am doing something wrong, this doesn't work for me:

`$ mkdir -p ~/testdir/testsubdir-to-exclude`
`$ touch ~/testdir/testsubdir-to-exclude/exclude_file`
`$ duplicati-cli test-filters ~/testdir --exclude=~/testdir/testsubdir-to-exclude/`
`Including folder: /home/macho/testdir/`
`Including folder: /home/macho/testdir/testsubdir-to-exclude/`
`Including file: /home/macho/testdir/testsubdir-to-exclude/exclude_file (unknown)`
`Matched 1 files (0 bytes)`

This is version 2.0.0.91-2.0.0.91_preview_2015-11-18

**Comment by mach-o** [comment]
@steilerDev : There's no release schedule. On the duplicati Google group, Kenneth has said that "[We do not have an ETA and do not put up timelines](https://groups.google.com/forum/#!searchin/duplicati/release/duplicati/yA5phuhUDSs/hnR2dq_Aqi0J)" at least in part because "[There are a relatively low number of contributors, and I don't know why that is](https://groups.google.com/forum/#!searchin/duplicati/release/duplicati/fFu8p4pA4uY/TGlmut1Hha8J)".

@kenkendk : maybe duplicati.com could be updated to reflect this state of affairs? Currently the prominent "Download duplicati" button does not make clear that it is linking to an unsupported version (1.3.4), which I have the sense is deprecated. Perhaps the 2.0 preview should be the most prominent release. The 2.0 preview, meanwhile, was last updated in July 2014, which will make visitors reasonably start to wonder whether this project has simply been abandoned. Perhaps it could also be made clear that development continues, but without a concrete release schedule, and that further contributors are welcome.

**Comment by steilerDev** [comment]
I see....thats a shame..

It's a great tool. Is there anyway to support you @kenkendk?

**Comment by kenkendk** [comment]
@mach-o: I can reproduce the filter issue. For some reason the `~` is not expanded in the filters part. I think the shell is supposed to expand it, but for some reason it does not.

Try this instead:
```
duplicati-cli test-filters ~/testdir --exclude=/home/macho/testdir/testsubdir-to-exclude/
```

That works for me.

**Comment by kenkendk** [comment]
@steilerDev: Good question. The best way to help out, is to start fixing things or adding features. Just grab whatever issue seems manageable to you. There is also the google groups forum which could use a few responders. If you are more into release planning, UX or similar you can contact @renestach.

**Comment by mach-o** [comment]
Thanks, @kenkendk, your modified example works for me too! Unfortunately, it doesn't fix the underlying problem that I was trying to illustrate with the example I concocted, which is that an `--exclude` of a root directory still doesn't seem to work:

`$ duplicati-cli test-filters / --exclude=/var`
`Including source path: /`
`Including folder: /`
`Including file: /core (285.37 MB)`
`Storing symlink: /initrd.img`
`Storing symlink: /initrd.img.old`
`Storing symlink: /vmlinuz`
`Storing symlink: /vmlinuz.old`
`Storing symlink: /initrd.img`
`Storing symlink: /initrd.img.old`
`Storing symlink: /vmlinuz`
`Storing symlink: /vmlinuz.old`
`Including folder: /var/`
`Including folder: /var/www/`
`Including folder: /var/www/html/`
`Including file: /var/www/html/index.html (11.06 KB)`
`Including folder: /var/tmp/`
<etc...>

Any further thoughts on why this might be?

**Comment by kenkendk** [comment]
Yes, you need to add the trailing slash to target a folder in a filter: 
```
duplicati-cli test-filters / --exclude=/var/
```

**Comment by mach-o** [comment]
Perfect! Thanks so much. I thought I had already tried this and had it fail, but it seems to be working.

**Comment by mrhahaz** [comment]
I to am having an issue like mach-o, not sure if something has changed since it was working for that user. What I am trying:

test-filters /home/kevin --exclude=/home/kevin/VirtualBox\ VMs/ --exclude=/home/kevin/GoogleDrive/ --exclude=/home/kevin/.thunderbird/ --exclude=/home/kevin/SharePoint/ --exclude=/home/kevin/.backups/ --exclude=/home/kevin/OneDrive/ --exclude=/home/kevin/nextcloud/ --exclude=*/.cache/ --exclude=*/cache/ --exclude=*/*cache/ --exclude=/home/kevin/scripts/ --exclude=/home/kevin/scriptsfiles/ --exclude=/home/kevin/.logs/ --exclude=/home/kevin/.wine/ --exclude=/home/kevin/.mozilla/ --exclude=*/gvfs-metadata/ --exclude=*/syncthing/ --exclude=*/.mono/ --exclude=*/evolution/ --exclude=*/chromium/ --exclude=*/Application\ Cache/ --exclude=/home/kevin/installs/


Correctly excludes the files specified in the exclude with a calculated size of ~900mb, I initially was using /VirtualBox\ VMs/ instead of the full path and the test was still including those files. So after some trying things ended up with the options above that WORK when I use test-filters. However, when I copy/paste those exact filters behind my backup command:

backup "file:///mnt/backup/home" "/home/kevin/" --log-level="Information" --log-file="/tmp/duplicati.log" --backup-name="home_backup" --passphrase="************" --dbpath="/home/kevin/.config/Duplicati/TUVQZAKXST.sqlite" --encryption-module="gpg" --compression-module="zip" --dblock-size="20gb" --keep-time="3M" -exclude....

It now begins creating backups in excess of 40Gb (most of that size is due to my VMs). Is there a different syntax I need to be using? Or am I missing something? I have tried creating this with the GUI and moved to using the command line after that didn't work. I tried changing my backup to path, database, job name and removing all temp files I could find.

Backup jobs where I don't need to exclude anything are working AWESOME! Once again in summary, when testing the filters my excludes work but when doing an actual backup either through the GUI or cli they do not.

**Pull request merged**
