### PR TITLE
make the delay for retry-after static 

### PR DESCRIPTION
**Pull request by gpatel-fr**
so it's kept when the backend is recreated - it happens every time the retry-after is set. 
Also, as having the cloud throttling the connection is a serious event, make it a warning instead of a profiling event so it will not be hidden from the user.

### CODE REVIEW

**Comment by gpatel-fr** [comment]
I don't parse the meaning for 'each backend that uses it'. There is only one backend that uses it: OneDrive. Maybe it was intended to be shared with other drivers but so far it has not happened. That's why I have modified it as if it was under the OneDrive directory, because for all intends and purposes it's the case.

**Comment by tygill** [comment]
A simple way to make it static per backend would be to have the helper take a `ref` parameter to track the state in. Each backend that wants to use it could then have its own static that it passes in each time it is called.

**Comment by kenkendk** [comment]
The intention of the `RetryAfterHelper` is that it should be a reusable component.
I see that this fix solves a problem, but I agree with @Jojo-1000 that this mixes the use of timeouts between backends.
If we add a new backend that uses the class it will now cause problems because the two backends can set each others wait times.

**Comment by kenkendk** [comment]
I added PR #5619 which has another take on this.
For the severity of the log message, I think it would be nice to have it visible, but on the other hand, it is something that can show up in a normal run, and is not really something the user can fix.

**Pull request closed without merging**
