### PR TITLE
fix bug in GetLargestPrefix() which adds an ending slash to file name

### PR DESCRIPTION
**Pull request by BlueBlock**
Do not apply AppendDirSeparator() to files.

For the section of code which handles files, AppendDirSeparator() is being applied to files when it should n't be at all. This results in all file paths to have an ending slash. This adjusted path causes the sql query to have 0 results.

For example:
GetLargestPrefix() would change D:\\myfiles\\photo1.jpg to be D:\\myfiles\\photo1.jpg\\

When the adjusted path is searched in the database it has 0 hits.

When debugging this can be tested by hitting the Restore and getting the file list for an existing backup job in the GUI.

### CODE REVIEW

**Comment by warwickmm** [comment]
@BlueBlock, can you clarify how to reproduce the issue here?  I haven't had any issues with restore and getting the file list.

**Comment by BlueBlock** [comment]
> @BlueBlock, can you clarify how to reproduce the issue here? I haven't had any issues with restore and getting the file list.

There doesn't appear to be any negative consequence to the bug. 

Running with the debugger and put a break on the line shown in an image below. Use an existing backup and select the Restore operation. The code will be hit when the file list gets pulled.

Without the fix, watch the values of "mp" and "foundfiles". "mp" will have the filename and an ending slash, which is invalid. So "foundFiles" will be 0.

Without fix:


With fix:

**Comment by warwickmm** [comment]
It looks like that line was introduced in revision 9a849a2b58943c53eeba995c7b78d39bfda95dac to fix some issues with cross-os restores.  Would this introduce a regression?

**Comment by BlueBlock** [comment]
> It looks like that line was introduced in revision [9a849a2](https://github.com/duplicati/duplicati/commit/9a849a2b58943c53eeba995c7b78d39bfda95dac) to fix some issues with cross-os restores. Would this introduce a regression?

The safest thing to do then would be to place this fix in an if/else for the OS.

I think I may need to try and confirm all the cases when DirectorySeparator is applied, at least under Windows, and see if it adds the slash elsewhere on files.

**Comment by warwickmm** [comment]
Unfortunately, I only have a Linux machine so I cannot help much with testing here.

**Comment by BlueBlock** [comment]
Added logic to apply it only to Windows

**Comment by warwickmm** [comment]
The original commit (9a849a2) mentions cross-os restores where the backup was created on Windows and the restore was performed on Mac/Linux.  Do we know how these changes might affect the other direction?  That is, backup on Mac/Linux and restore on Windows?

**Comment by BlueBlock** [comment]
> The original commit ([9a849a2](https://github.com/duplicati/duplicati/commit/9a849a2b58943c53eeba995c7b78d39bfda95dac)) mentions cross-os restores where the backup was created on Windows and the restore was performed on Mac/Linux. Do we know how these changes might affect the other direction? That is, backup on Mac/Linux and restore on Windows?

It wouldn't affect another platform since it is only reading data and the code is restricted to Windows with the original code for other platforms. So it seems there would be no affect?

**Comment by warwickmm** [comment]
I don't understand why the directory separator is needed in any case, so the main concern is introducing a regression.  Even though the modifications are restricted to Windows, it's not clear to me if this affects how a Linux backup is restored on Windows.

@BlueBlock, is your setup able to test some simple cross-os backup/restores?

**Comment by BlueBlock** [comment]
I can try with a linux dev machine I have setup.

**Comment by BlueBlock** [comment]
I tested and was able to backup/restore across Windows/Linux without a problem.

**Comment by warwickmm** [comment]
That's great!  In fact, would you mind running your tests with the fix applied to all platforms (not just Windows)?  I don't understand why the directory separator is needed in any case.

**Comment by BlueBlock** [comment]
I'll give it a test.

**Comment by BlueBlock** [comment]
The issue also happens on linux so the fix should apply to all systems. New commit added.

**Comment by warwickmm** [comment]
Sounds good to me.  Thanks @BlueBlock.

**Pull request merged**
