### PR TITLE
DuplicatiVerify powershell

### PR DESCRIPTION
**Pull request by mnaiman**
Converted python script to powershell for machines where is not powershell installed

### CODE REVIEW

**Comment by mnaiman** [comment]
It is possible to bundle these scripts to installation folder, eg. tools, or scripts?

**Comment by kenkendk** [comment]
Thanks for this!

**Comment by kenkendk** [comment]
I think these tools should be bundled, but currently they are not.

Right now the "commandline" project is pulling in the "win-tools" folder.
We could tack on the scripts to this, or create an empty project that has installer items?

**Comment by mnaiman** [comment]
I vote for empty project, not to bundle with commandline

**Pull request merged**
