### PR TITLE
Add stylelint and edit README.md

### PR DESCRIPTION
**Pull request by luixxiul**
Closes https://github.com/duplicati/duplicati/issues/5451

This PR intends to add [stylelint](https://stylelint.io) with its [Less plugin](https://www.npmjs.com/package/stylelint-config-standard-less), editing the instruction to have the Less packages installed for the project only. IMHO it is not quite necessary to have them installed globally, which may require root privilege.

With this PR it should be possible to lint and compile style rules with `npm run-script` as well: 

- `npm run lint:style` (lint style rules without fixing errors)
- `npm run lint:style-fix` (lint style rules with fixing errors)
- `npm run build:style` (lint style rules *with* fixing errors before compiling Less files)

I set up a new VM and checked those commands work on Debian by following the instruction on README.md.

Please note that using Stylelint should not affect possible migration to Angular as the linter generally does not change style rules substantially.

Signed-off-by: Suguru Hirahara <luixxiul@users.noreply.github.com>

### CODE REVIEW

**Comment by luixxiul** [comment]
`package-lock.json` was added for `npm ci`: https://docs.npmjs.com/cli/v10/commands/npm-ci/

**Comment by luixxiul** [comment]
Since the README.md has used the word "compile", `npm run compile:style` should be good to go.

**Comment by luixxiul** [comment]
I am wondering if this would be merged or not...

**Comment by kenkendk** [comment]
Sorry, lost this PR in the noise!

**Pull request merged**
