### PR TITLE
Fix Amazon Cloud Drive and Box backends

### PR DESCRIPTION
**Pull request by warwickmm**
This fixes an issue where the  Amazon Cloud Drive and Box backends would fail for larger uploads.  These two backends are the only ones that use the `JSONWebHelper.PostMultipartAsync` method.  In pull request #3684, we replaced the use of `AsyncHttpRequest.GetRequestStream` with `HttpRequest.GetRequestStreamAsync`.  For some reason, this broke the upload operations so we are reverting that change here.

This fixes issue #3756.

### CODE REVIEW

**Comment by warwickmm** [comment]
I don't understand why the `async` version doesn't work, but with these changes my Amazon Cloud Drive and Box tests are passing again.  @seantempleton and @kenkendk, any insight here?

**Comment by warwickmm** [comment]
One of the errors I was encountering:
```
"ClassName":"System.ObjectDisposedException","Message":"Cannot access a disposed object.","Data":null,"InnerException":null,"HelpURL":null,"StackTraceString":" at Mono.Net.Security.MobileAuthenticatedStream.StartOperation (Mono.Net.Security.MobileAuthenticatedStream+OperationType type, Mono.Net.Security.AsyncProtocolRequest asyncRequest, System.Threading.CancellationToken cancellationToken) [0x00245] in /build/mono/src/mono/mcs/class/System/Mono.Net.Security/MobileAuthenticatedStream.cs:533
at System.Net.WebRequestStream.ProcessWrite (System.Byte[] buffer, System.Int32 offset, System.Int32 size, System.Threading.CancellationToken cancellationToken) [0x00229] in /build/mono/src/mono/mcs/class/System/System.Net/WebRequestStream.cs:246
at System.Net.WebRequestStream.WriteAsyncInner (System.Byte[] buffer, System.Int32 offset, System.Int32 size, System.Net.WebCompletionSource completion, System.Threading.CancellationToken cancellationToken) [0x001aa] in /build/mono/src/mono/mcs/class/System/System.Net/WebRequestStream.cs:195
at Duplicati.Library.JSONWebHelper.PostMultipartAsync (System.String url, System.Action`1[T] setup, System.Threading.CancellationToken cancelToken, Duplicati.Library.MultipartItem[] parts) [0x0037c] in /home/warwickmm/documents/code/duplicati/Duplicati/Library/Backend/OAuthHelper/JSONWebHelper.cs:148
at Duplicati.Library.JSONWebHelper.PostMultipartAndGetJSONDataAsync[T] (System.String url, System.Action`1[T] setup, System.Threading.CancellationToken cancelToken, Duplicati.Library.MultipartItem[] parts) [0x00041] in /home/warwickmm/documents/code/duplicati/Duplicati/Library/Backend/OAuthHelper/JSONWebHelper.cs:91
at Duplicati.Library.Backend.AmazonCloudDrive.AmzCD.PutAsync (System.String remotename, System.IO.Stream stream, System.Threading.CancellationToken cancelToken) [0x002b6] in /home/warwickmm/documents/code/duplicati/Duplicati/Library/Backend/AmazonCloudDrive/AmzCD.cs:359
at Duplicati.Library.Main.Operation.Backup.BackendUploader.DoPut (Duplicati.Library.Main.Operation.Common.BackendHandler+FileEntryItem item, Duplicati.Library.Interface.IBackend backend, System.Threading.CancellationToken cancelToken) [0x00460] in /home/warwickmm/documents/code/duplicati/Duplicati/Library/Main/Operation/Backup/BackendUploader.cs:387
at Duplicati.Library.Main.Operation.Backup.BackendUploader+<>c__DisplayClass17_0.<UploadFileAsync>b__0 () [0x000f3] in /home/warwickmm/documents/code/duplicati/Duplicati/Library/Main/Operation/Backup/BackendUploader.cs:264
at Duplicati.Library.Main.Operation.Backup.BackendUploader.DoWithRetry (System.Func`1[TResult] method, Duplicati.Library.Main.Operation.Common.BackendHandler+FileEntryItem item, Duplicati.Library.Main.Operation.Backup.BackendUploader+Worker worker, System.Threading.CancellationToken cancelToken) [0x0016e] in /home/warwickmm/documents/code/duplicati/Duplicati/Library/Main/Operation/Backup/BackendUploader.cs:286 ","RemoteStackTraceString":null,"RemoteStackIndex":0,"ExceptionMethod":null,"HResult":-2146232798,"Source":"mscorlib","ObjectName":"MobileAuthenticatedStream"}
```

**Comment by kenkendk** [comment]
Not sure why it happens, but the error indicates that some code progresses and disposes the instance before it can be written. It looks correct, but maybe the `ConfigureAwait` call messes it up as it looses the context and the `HttpRequest` needs the context for something?

**Comment by warwickmm** [comment]
Unfortunately, removing the `ConfigureAwait` does not fix the issue.  Removing the use of `AsyncHttpRequest` may require some more thorough investigation.

**Comment by seantempleton** [comment]
Sorry, I missed this.

Any idea if this is a Mono only problem? There was a somewhat similar bug fixed early last year in Mono in MobileAuthenticatedStream. I'm guessing you're using the latest version of Mono though @warwickmm. Ultimately I suspect you're right, that the changes to `PostMultipartAsync` caused this.

I'll try and see if there's some way I can reproduce this without having an ACD account.

**Comment by warwickmm** [comment]
Thanks.  I'm using mono 5.20.1, which I think is the latest stable release.

**Pull request merged**
