### PR TITLE
Prevent progress bar from obscuring stop button

### PR DESCRIPTION
**Pull request by jfparis**
Brings the Stop button above the progress bar to allow stopping tasks even when they are well advanced

This should address issue #4436

### CODE REVIEW

**Comment by warwickmm** [comment]
Thanks @jfparis.  However, we actually generate `style.css` by editing [Duplicati/Server/webroot/ngax/less/style.less](https://github.com/duplicati/duplicati/blob/v2.0.5.112-2.0.5.112_canary_2021-01-20/Duplicati/Server/webroot/ngax/less/style.less) and then compiling it with `lessc`
```
$ lessc Duplicati/Server/webroot/ngax/less/style.less --clean-css > Duplicati/Server/webroot/ngax/styles/style.css
```
Would you be able to make your changes to `style.less`?

**Comment by jfparis** [comment]
This got out of hand quickly.
Lessc seems to have dropped a lot of quotes out of the compiled file. Not sure if this is causing the rest of the trouble. Is there a specific version of lessc? Is there a specific devenv that I can replicate?

**Comment by jfparis** [comment]
The trick is in the "-x" parameter for less. I will update the PR
Thanks

**Comment by warwickmm** [comment]
Thanks @jfparis.  Looks good to me on Brave.  @drwtsn32x, are you able to test this on a few other browsers?

**Comment by drwtsn32x** [comment]
@warwickmm - worked for me on Firefox.  Brave is Chromium-based right, so it should also work with regular Chrome or Edge as well.

**Comment by warwickmm** [comment]
Thanks @drwtsn32x.

I also compiled `style.less` locally and the resulting `style.css` was identical to what was committed.

**Comment by drwtsn32x** [comment]
@warwickmm @jfparis - something may be wrong with this change.  Now I'm seeing this when editing a backup job:

Capture

**Comment by warwickmm** [comment]
Thanks @drwtsn32x, I see it too.  @jfparis, are you able to reproduce this?

I'll revert the merge in `master`.

**Comment by jfparis** [comment]
Yes. I can see it. I need to figure out whether this is a compiler issue or
else
--
Jean-François Paris
+44 7533414619

**Comment by jfparis** [comment]
Figured it out. This was a compiler issue.
The proper way to invoke lessc is 
`lessc -m=always -x Duplicati/Server/webroot/ngax/less/style.less > Duplicati/Server/webroot/ngax/styles/style.css` 

Both options are deprecated :)

WIll submit a new PR

**Pull request merged**
