### PR TITLE
Added support for certificates under Linux

### PR DESCRIPTION
**Pull request by mnaiman**

### CODE REVIEW

**Comment by mnaiman** [comment]
Bug https://github.com/duplicati/duplicati/issues/2133

**Comment by kenkendk** [comment]
There is a build error on Linux:
```
Errors:

/home/travis/build/duplicati/duplicati/Duplicati.sln (default targets) ->
(Build target) ->
/home/travis/build/duplicati/duplicati/Duplicati/Server/Duplicati.Server.csproj (default targets) ->
/usr/lib/mono/xbuild/14.0/bin/Microsoft.CSharp.targets (CoreCompile target) ->

	Database/ServerSettings.cs(23,7): error CS0246: The type or namespace name `Org' could not be found. Are you missing an assembly reference?
	Database/ServerSettings.cs(24,7): error CS0246: The type or namespace name `Org' could not be found. Are you missing an assembly reference?
	Database/ServerSettings.cs(25,7): error CS0246: The type or namespace name `Org' could not be found. Are you missing an assembly reference?

	 18 Warning(s)
	 3 Error(s)
```

**Comment by kenkendk** [comment]
It seems to find the assembly, but in one place it has:

```
/usr/lib/mono/xbuild/14.0/bin/Microsoft.Common.targets:  warning : Reference 'BouncyCastle.Crypto, Version=1.8.1.0, Culture=neutral, PublicKeyToken=0e99375e54769942' not resolved
				For searchpath {CandidateAssemblyFiles}
				Warning: {CandidateAssemblyFiles} not supported currently
				For searchpath {HintPathFromItem}
				Considered ../../../../packages/BouncyCastle.1.8.1/lib/BouncyCastle.Crypto.dll, but it does not exist.
				For searchpath {TargetFrameworkDirectory}
				Considered target framework dir /usr/lib/mono/4.5-api/, assembly named 'BouncyCastle.Crypto' not found.
				Considered target framework dir /usr/lib/mono/4.5-api//Facades/, assembly named 'BouncyCastle.Crypto' not found.
				For searchpath {PkgConfig}
				Considered BouncyCastle.Crypto, Version=1.8.1.0, Culture=neutral, PublicKeyToken=0e99375e54769942, but could not find in any pkg-config files.
				For searchpath {GAC}
				Considered BouncyCastle.Crypto, Version=1.8.1.0, Culture=neutral, PublicKeyToken=0e99375e54769942, but could not find in the GAC.
				For searchpath {RawFileName}
				Considered 'BouncyCastle.Crypto, Version=1.8.1.0, Culture=neutral, PublicKeyToken=0e99375e54769942' as a file, but the file does not exist
				For searchpath bin/Release/
				Considered '/home/travis/build/duplicati/duplicati/Duplicati/Server/bin/Release/BouncyCastle.Crypto' as a file, but the file does not exist
				Considered '/home/travis/build/duplicati/duplicati/Duplicati/Server/bin/Release/BouncyCastle.Crypto.exe' as a file, but the file does not exist
				Considered '/home/travis/build/duplicati/duplicati/Duplicati/Server/bin/Release/BouncyCastle.Crypto.dll' as a file, but the file does not exist
```

**Comment by mnaiman** [comment]
I have copied same reference what is in other project of solution - Duplicati.Library.Modules.Builtin.csproj

```
    <Reference Include="BouncyCastle.Crypto, Version=1.8.1.0, Culture=neutral, PublicKeyToken=0e99375e54769942">
      <HintPath>..\..\..\..\packages\BouncyCastle.1.8.1\lib\BouncyCastle.Crypto.dll</HintPath>
      <Private>True</Private>
    </Reference>
```
Maybe Private is missing

**Comment by kenkendk** [comment]
It is strange if it does not work, I have tested this setup on OSX with Mono:
https://github.com/kenkendk/ceenhttpd/blob/master/Ceen.Httpd/ServerConfig.cs#L162

It correctly loads the SSL certificate. The only difference I see is that the one in Duplicati is using a string rather than a file. 

I used these commands to create the pfx file, which I believe is PKCS12:
https://github.com/kenkendk/ceenhttpd/blob/master/Ceen.Httpd.Cli/example_config.txt#L37

If we go with this fix, we would need to add a license entry for BouncyCastle (can be done later).
Did you get the BouncyCastle approach to work on Ubuntu 14.04 ?

**Comment by mnaiman** [comment]
1) certficate is working fine, what was not working on Linux was serialization of X509Certificate2 to string to be stored in database in form of BASE64 (mono doesnt support Export function)
2) BouncyCastle is already used in Duplicati, I have only referenced it

**Pull request merged**
