### PR TITLE
Added support for passing arguments to scripts

### LINKED ISSUE #2926: Arguments for scripts before/after options
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.2.1-1
- **Operating system**: Ubuntu 16.04.3 LTS
- **Backend**: local filesystem

## Description

I need to call a script with arguments but when I call the task I get:

`ApplicationName='/home/foo/bar.sh jhon doe', CommandLine='', CurrentDirectory='', Native error= Cannot find the specified file`

## Steps to reproduce

1. Install duplicati
2. Configure a backup with the option `run-script-before-required`
3. Give to your scripts arguments

- **Actual result**:
The backup fails with this log `ApplicationName='/home/foo/bar.sh jhon doe', CommandLine='', CurrentDirectory='', Native error= Cannot find the specified file`
- **Expected result**:
The backup calls the script `'/home/foo/bar.sh` sending `jhon` and `doe' as arguments.

Thanks

### PR DESCRIPTION
**Pull request by kenkendk**
This closes #2926

### CODE REVIEW

**Comment by energywave** [comment]
Wonderful that you took time to do that, thank you so much just for that!
To discsuss the implementation (constructive criticism):
1.  did you test those even in Windows?
2. Would not have been easier to use the standard syntax like: `"c:\path with spaces\mybatch.cmd" arg1 "arg 2 with spaces"` ?
3. Or maybe, even better, just pass them to the shell to execute so that it's up to the user to write a correct syntax for the OS in use? I don't get why to separate arguments from the commandline.
4. I'm sceptical about the json syntax. I appreciate the possibility and welcome it but thinking about Duplicati that's used by all kind of people and must keep it simple, that will be not so understandable by many persons.

However thank you for the implementation!

**Comment by kenkendk** [comment]
Thanks for the feedback @energywave !

1. No, I do not see anything that is Windows specific here. 
Do you see anything that would break on Windows?

2. My primary concern is backwards compatibility. 
If users have set it up to run a script with spaces in the path, it will break if we start to parse the path.
But I like the syntax! I am used to escaping spaces, so I had not thought of that.

3. I have not seen the option to pass arguments directly to the shell from C#:
https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.process.start?view=net-8.0
It all requires at least parsing the executable name.
I will experiment with passing the rest of the string without modification.

4. It is overkill for most users, but when dealing with tricky escape rules, I find it easier to just use a standard JSON encoding.
I do not think the separation of arguments and commandline is useful either, it was just an easy way to preserve compatibility with the previous non-parsing of the argument.

**Comment by kenkendk** [comment]
I have made a new approach here, based on your suggestion.

The logic is now that nothing extra is needed.
You just add the arguments to the script as suggested, optionally using single or double quotes to group arguments.

There is a small possibility that this will break existing setups because the script path was previously treated as a single path, but is now treated as a commandline. I think I will address this in the release notes.

**Comment by Jojo-1000** [comment]
Have you checked how this affects command line users? I would imagine they need to double escape the strings, which is annoying but there isn't really a way around it.

For space splitting, does the Linux way of escaping spaces with a backslash before them also work?

I have to say I liked the backwards compatible version. I quite often have spaces in my paths, but on the other hand the syntax is unusual and more complexity is not really what we need.

**Comment by Jojo-1000** [comment]
> 3\. Or maybe, even better, just pass them to the shell to execute so that it's up to the user to write a correct syntax for the OS in use? I don't get why to separate arguments from the commandline.

This could also fix the existing issue that Powershell scripts are not executed automatically, if such a way exists.

**Comment by energywave** [comment]
> Thanks for the feedback @energywave !

Thanks to you that implemented it!

> 1. No, I do not see anything that is Windows specific here.
>    Do you see anything that would break on Windows?

No, I don't, I took a look at the code, seems ok to me (but real life tests are a good option :) )

> 3. I have not seen the option to pass arguments directly to the shell from C#:

Yes sorry, I didn't remember that, you're right. We need to detect where executable path ends and arguments starts. I've checked in my softwares where I do such things and I implemented a function to split entire commandline by iterating characters and keeping tracks of "in apix" or "outside apix" state while progressing, until I find a space outside apixes to split the commandline in executable path and arguments. Does not need to split arguments, however, just passing then "as is" to the `Process.Start` function

> I have made a new approach here, based on your suggestion.

Hey, I'm honored you liked my suggestion and implemented it, thank you!

> There is a small possibility that this will break existing setups because the script path was previously treated as a single path, but is now treated as a commandline. I think I will address this in the release notes.

To avoid that (just an idea) you could add a new parameter, something like `--run-script-syntax` or maybe `--run-script-with-arguments` to switch the new behavior on or off with default off, so that existing users will have no change and will not have any malfunctions.
I'm with you that keeping backward compatible changes is a good practice as a strict minority of users really reads changelogs... :_(

> For space splitting, does the Linux way of escaping spaces with a backslash before them also work?

It could be theorically possible to detect both ways but the author implemented this using regex and I don't know if the regex can be modified to handle that (I personally hate regexes... :D )
With the function I've made (talked about that above) it could be easy to add also that.
But let's hear what @kenkendk thinks about it.

> I have to say I liked the backwards compatible version. I quite often have spaces in my paths, but on the other hand the syntax is unusual and more complexity is not really what we need.

Could adding a switch option with the old default, like proposed above, be a good choice for you?

**Comment by ts678** [comment]
[System.Diagnostics.ProcessStartInfo.UseShellExecute property](https://learn.microsoft.com/en-us/dotnet/fundamentals/runtime-libraries/system-diagnostics-processstartinfo-useshellexecute) says it's not a command shell (e.g. specifically disclaiming bash).

**Comment by energywave** [comment]
> [System.Diagnostics.ProcessStartInfo.UseShellExecute property](https://learn.microsoft.com/en-us/dotnet/fundamentals/runtime-libraries/system-diagnostics-processstartinfo-useshellexecute) says it's not a command shell (e.g. specifically disclaiming bash).

From what I know UseShellExecute is used in Windows to "execute" a document, like an Excel spreadsheet file, to let Windows open it with the corresponding executable assigned in Windows Settings.
The article claims that "Shell" is not to be intended as "Linux shell". I'll cite:

`The word "shell" in this context (UseShellExecute) refers to a graphical shell (similar to the Windows shell) rather than command shells (for example, bash or sh) and lets users launch graphical applications or open documents.`

If set to False you can just execute "real" executables.
So I don't think that should be relevant in this discussion. Hoping to not miss something, in that case I'm sorry.

**Comment by kenkendk** [comment]
> Have you checked how this affects command line users? I would imagine they need to double escape the strings, which is annoying but there isn't really a way around it.
> 
> I have to say I liked the backwards compatible version. I quite often have spaces in my paths, but on the other hand the syntax is unusual and more complexity is not really what we need.

Yes, that was my motivation for the original approach. I was thinking of how to support spaces in paths, and I wanted to avoid inventing something new, so I went for JSON, which handles all sorts of edge cases and is well known.

I was considering adding a compatibility switch like `--run-script-no-argument-parsing` (or similar), but I think it adds complexity with very little gain.

> For space splitting, does the Linux way of escaping spaces with a backslash before them also work?

Not right now, but it can be added. Not sure how to correctly support that on Windows which has slightly complex rules because backslash is both a valid path character and an escape character.

> Does not need to split arguments, however, just passing then "as is" to the `Process.Start` function

That is an option, but I think that is slightly inconsistent, because you then have different ways to escape the arguments and the executable.

> This could also fix the existing issue that Powershell scripts are not executed automatically, if such a way exists.

@Jojo-1000 Do you know why this happens? Is it because `.ps` files need to be invoked with `UseShellExecute=true` ?

If this is the case, we could either autodetect it or add `--run-script-use-shell-execute`.

> maybe `--run-script-with-arguments`

Yes, that would maintain backwards compatibility. @Jojo-1000 would it work for your use as well?

**Comment by Jojo-1000** [comment]
> Do you know why this happens? Is it because `.ps` files need to be invoked with `UseShellExecute=true` ?

The reason why powershell scripts don't work by default is that, unlike .bat, the .ps1 extension is not registered with the executable in Windows (for double click). So you either need to register it, which has some security concern, or invoke it with `powershell.exe -file script.ps1`. That would be possible now with this support for arguments.
I don't know if UseShellExecute makes any difference.
https://github.com/duplicati/duplicati/issues/4290

**Comment by energywave** [comment]
> I would assume this would actually enable the `.ps1` extension to execute, but unfortunately we cannot use it because launching with `UseShellExecute = true` is not possible when also redirecting stdout or stderr.

But I think it's not needed, as stated by @Jojo-1000 : by using arguments you can now specify `powershell.exe -file script.ps1` that will handle powershell scripts by using the powershell version between the installed ones of your choice.

About the baskslash escaping you're right, it would be needed to enable it only on Linux, not on Windows as there is the path separator.

**Pull request merged**
