### PR TITLE
Fix compile for vs mac

### PR DESCRIPTION
**Pull request by tgorgdotcom**
This is a "Part 1" to fix the issues with newer versions of MacOS and Python.  This part enables us to get duplicati compiled on VS for Mac (and perhaps Xamarin Studio, etc.).  It primarily adds bouncycastle back in as a referenced packaged (as it's still being used in MailKit/MimeKit packages).  It also upgrades a few packages (a side effect of the process I was using to reinstall packages).

"Part 2" will come from @dgileadi, and include fixes to get the Duplicati.GUI.TrayIcon CocoaRunner class working, hopefully enabling us to deprecate the RumpsRunner class, and free us of the Python dependency.

### CODE REVIEW

**Comment by warwickmm** [comment]
Are the build issues specific to macOS 12?  The [tests](https://github.com/duplicati/duplicati/runs/7481911990?check_suite_focus=true) are running on macOS 11 without any problems and I believe @kenkendk builds and creates the releases on a mac (not sure what version).

**Comment by tgorgdotcom** [comment]
Hello @warwickmm.  Not sure if it's MacOS 12 specific, but I get issues when starting from pulling fresh from the repository.    There's [a reference in issue #4468](https://github.com/duplicati/duplicati/issues/4668#issuecomment-1189385567) that details what's going on from another user.  I think the lines removed in pull request #4584 might have introduced the bug (removed reference to BouncyCastle).

**Comment by warwickmm** [comment]
I don't have a mac, but a [test build](https://github.com/warwickmm/duplicati/runs/7623897217?check_suite_focus=true) with macOS 12.5 appears to compile without error.  It would be nice if we can get a better understanding of how the build environments differ.

**Comment by warwickmm** [comment]
Sorry, I just saw the stack trace [here](https://github.com/duplicati/duplicati/issues/4668#issuecomment-1189385567).  Is the issue a runtime error and not a compile time error?

**Comment by tgorgdotcom** [comment]
It seems to happen as the debug is starting, after the build process.

**Comment by tgorgdotcom** [comment]
Hmm.  I pulled a fresh copy of the codebase and I ran the tests manually via command line.  I get 6 errors, (only 3 provide stack traces), but it does look like duplicati runs completely, and the stack traces are not related to the errors I've been getting in Visual Studio for Mac.  

I also tried an additional fresh copy of the codebase and opened that in VS, in the hopes doing so would determine if VS is doing something different from `nuget restore Duplicati.sln`.  It does do a restore of the packages automatically, and running a build works okay (up to the point that it errors when it's looking for Python).

**However**, it's when I start making changes to Duplicati.GUI.TrayIcon and CocoaRunner when I start getting the error that @dgileadi also gets in [issue #4668](https://github.com/duplicati/duplicati/issues/4668#issuecomment-1189385567).  I essentially modify this to use Xamarin.Mac instead of Mono.Mac (including modifying references files to the correct dlls).  Perhaps I should ask @dgileadi to include the reference in his pull request that will include the switch to Xamarin.Mac for CocoaRunner?

**Comment by dgileadi** [comment]
Yes, it sounds like the reference changes are tied up with using Xamarin.Mac. I didn't expect that.

I'll go ahead and make a PR with my changes, including the reference changes, and see how that goes. Thanks @tgorgdotcom for all your help with this!

**Pull request closed without merging**
