### PR TITLE
Prepared for new Uplink packages that correctly package the Storj binaries

### PR DESCRIPTION
**Pull request by kenkendk**
For now there is still an issue with the linux versions: https://github.com/TopperDEL/uplink.net/issues/39#issuecomment-2217243464

### CODE REVIEW

**Comment by luixxiul** [comment]
Will this close https://github.com/duplicati/duplicati/issues/5226 maybe?

**Comment by kenkendk** [comment]
@luixxiul I assume it will. Merging this PR should make Storj work on all platforms except Linux non-x64. I am waiting a bit to see if @TopperDEL can make an updated Linux package, so we can close it all in one go.

**Comment by TopperDEL** [comment]
Please use version 2.13.3484 for uplink.NET. It now includes the correct binaries.
I missed the fact that during build the target-architecture was not respected and therefore was always the one from the host (x64).

And yes @luixxiul: this should close #5226 - at least from the uplink.NET-perspective.

**Comment by kenkendk** [comment]
@TopperDEL Great! I can confirm it now has the correct library for all builds.

**Pull request merged**
