### PR TITLE
Fix error encountered during dry-run of purge-broken-files

### LINKED ISSUE #4379: Command purge-broken-files throws SQLiteException 0x80004005 unknown error
- [x] I have searched open and closed issues for duplicates.

## Environment info
- **Duplicati version**: 2.0.5.111_canary_2020-09-26
- **Operating system**: Windows 10 Enterprise, version 20H2 
- **Backend**: Local (network mapped drive to another Windows 10 machine on the same LAN)

## Description
Command **purge-broken-files** fails with System.Data.SQLite.SQLiteException (0x80004005): unknown error.

## Steps to reproduce
1. Open the Duplicati UI, go to the backup, command line...
2. Pick purge-broken-files, provide one command-line argument --dry-run
3. Scroll to bottom, click **Run "purge-broken-files" command now** button

- **Actual result**:

```
  Listing remote folder ...

code = Unknown (-1), message = System.Data.SQLite.SQLiteException (0x80004005): unknown error
No transaction is active on this connection
   at System.Data.SQLite.SQLiteTransactionBase.IsValid(Boolean throwError)
   at System.Data.SQLite.SQLiteTransactionBase.Rollback()
   at Duplicati.Library.Main.Operation.PurgeBrokenFilesHandler.Run(IFilter filter)
   at Duplicati.Library.Main.Controller.RunAction[T](T result, String[]& paths, IFilter& filter, Action`1 method)
   at Duplicati.Library.Main.Controller.PurgeBrokenFiles(IFilter filter)
   at Duplicati.CommandLine.Commands.PurgeBrokenFiles(TextWriter outwriter, Action`1 setup, List`1 args, Dictionary`2 options, IFilter filter)
   at Duplicati.CommandLine.Program.ParseCommandLine(TextWriter outwriter, Action`1 setup, Boolean& verboseErrors, String[] args)
   at Duplicati.CommandLine.Program.RunCommandLine(TextWriter outwriter, TextWriter errwriter, Action`1 setup, String[] args)
Return code: 100
```

- **Expected result**:
Command should complete successfully and delete broken files from the existing backups.

## Full Story

I created a new backup of my user home directory on Windows, approx. 30 GB, 190 thousand files. First backup got stuck because of #1797 or #4308. So i rebooted the computer, added an exclusion for `AppData\Local\Duplicati\`, started the backup again and it completed successfully. Few days later, out of curiosity, I restored some selected files (worked fine) and also ran a command `test all --full-remote-verification`. That returned one broken dblock. I confirmed with SharpAESCrypt.exe that the file is really corrupted (other files are good).

I renamed the file on the target storage (read: deleted). Now backup fails with error

> Found 1 files that are missing from the remote storage, please run repair

Okay, so I ran the repair command, which failed with error:

> The backup storage destination is missing data files. You can either enable `--rebuild-missing-dblock-files` or run the purge command to remove these files. The following files are missing: duplicati-bdc7e234b7b5f40c5869f459d72a0e88a.dblock.zip.aes

Okay, rebuilding missing dblock files sounds great, but it failed with:

> Failed to perform cleanup for missing file: duplicati-bdc7e234b7b5f40c5869f459d72a0e88a.dblock.zip.aes, message: Repair not possible, missing 595 blocks. If you want to continue working with the database, you can use the "list-broken-files" and "purge-broken-files" commands to purge the missing data from the database and the remote storage.

Since repair is not getting me anywhere, let's purge the existing backups (with a limited data loss), the future backups should fix the missing/purged files, that's okay with me. However, the purge command fails with the SQLiteException -- which is this GitHub issue.

### PR DESCRIPTION
**Pull request by warwickmm**
This is an attempt to avoid an error that is encountered during a dry-run of `purge-broken-files`.

The `PurgeFilesHandler` begins new transactions using the same database connection as the `PurgeBrokenFilesHandler`.  During a  dry-run, these transactions are rolled back, and a subsequent attempt to rollback in the `PurgeBrokenFilesHandler` then resulted in an exception.  To avoid this, we perform the rollback in the `PurgeBrokenFilesHandler` as soon as we can, before new transactions are created and rolled back.

This also adds a situation to the `PurgeBrokenFilesTest` test to illustrate the issue described in issue #4379. 

This fixes #4379.

### CODE REVIEW

**Comment by warwickmm** [comment]
I have limited understanding with SQLite so I'm not entirely confident that this is the correct fix, but it does appear to resolve issue #4379.  Hopefully it doesn't introduce any new bugs or side effects.

**Comment by kenkendk** [comment]
It looks correct to me

**Comment by ts678** [comment]
Above forum report seems to have gotten this in 2.0.5.1, and I'm not sure what information to collect. Speak up if you like.

**Comment by warwickmm** [comment]
It looks to me that this change was first released in 2.0.5.112, correct?

**Comment by ts678** [comment]
> released in 2.0.5.112

My off-by-one on the year... I was looking for Dec 19 a year ago, and thinking 2.0.4.38_canary_2019-12-29 which just preceded the Experimental that became 2.0.5.1 Beta, 2.0.5.112_canary_2021-01-20 fits right for Dec 19 (2020) and also has a credit line that says:

> Fixed error that occured when using the dry-run option of purge-broken-files, thanks @warwickmm

I updated the forum post with the correct release.

**Pull request merged**
