### PR TITLE
Progress on #2578

### PR DESCRIPTION
**Pull request by Danstahr**
Progress on the individual tasks of the issue:

- [x] Remove all uses of VACUUM in the code
- [x] Add a commandline vacuum command that allows manual activation
- [ ] Add a "Reclaim space" button in the UI that calls the vacuum operation
- [x] Add a --auto-vacuum option that calls the vaccum command after an operation

### CODE REVIEW

**Comment by kenkendk** [comment]
Looks great!

The backup does not call vaccum directly, but it calls it through this method:
https://github.com/Danstahr/duplicati/blob/58a95e03e606894deea83ca3e4365e76c410e9ea/Duplicati/Library/Main/Database/LocalDatabase.cs#L1307

**Comment by Danstahr** [comment]
Good catch! I did search for all vacuum references but missed this one.

Fixed.

**Comment by kenkendk** [comment]
The Travis error is from SharpCompress. Could you pull in master and see if it fixes the build?

**Comment by Danstahr** [comment]
Done.

**Comment by kenkendk** [comment]
It is strange that the fix is required, as it just changes the folder name to camel-case, instead of lowercase. Tests have been working without that fix for months.

**Pull request merged**
