### PR TITLE
Dns resolution failure

### PR DESCRIPTION
**Pull request by Pectojin**
Initial solution to #2972

We'll need to create `DNSName` methods for each backend at some point, but no reason to delay this fix until all backends are implemented.

### CODE REVIEW

**Comment by kenkendk** [comment]
Should the non-implemented ones perhaps return `null` instead, so we do not get nonsense warnings when trying to refresh? So if `DNSName == null` we don't try the DNS refresh?

**Comment by kenkendk** [comment]
> GetHostEntry throws an error if it fails to find the DNS name, even when it's valid input.

Yes, but I was thinking that those who do not implement the feature, does not have to raise an additional error?

Specifically, the file backend will never implement it (granted, it might not throw `NameResolutionError`), so if the check was like this it would not risk problems:

```csharp
try
{
    if (!string.IsNullOrWhiteSpace(m_backend.DNSName))
        System.Net.Dns.GetHostEntry(m_backend.DNSName);
}
catch
{
    Logging.Log.WriteMessage("Failed to resolve IP for " + m_backend.DNSName, Logging.LogMessageType.Warning);
}
```

Btw, the error handler crashes as well, if you ever get here as it accesses `DNSName` too.

**Comment by Pectojin** [comment]
Oh... silly me... I didn't think about the error handler.

I'll update them to return null and add some checks.

**Comment by Pectojin** [comment]
Changed from `NotYetImplemented` to return null.

I also removed the logging case because I realized it was totally redundant.
screen shot 2018-02-21 at 22 23 32

**Pull request merged**
