### PR TITLE
Set snapshot-policy to auto by default

### PR DESCRIPTION
**Pull request by samuel-w**
Fixes https://github.com/duplicati/duplicati/issues/2833

### CODE REVIEW

**Comment by warwickmm** [comment]
I'm not sure this is a good idea.  I believe `snapshot-policy` requires administrator/root privileges, and also doesn't work on MacOS.

**Comment by samuel-w** [comment]
In auto mode, it tries and fails silently, according to the description:
> Setting this to "auto" makes Duplicati attempt to create a snapshot, and fail silently if that was not allowed or supported (note that the OS may still log system warnings).

**Comment by warwickmm** [comment]
There's some discussion [here](https://forum.duplicati.com/t/ignore-locked-files/4326/5) about `snapshot-policy=auto` causing audio/visual notifications in Windows, which would be quite annoying.  What OS are you testing on?

@ts678, @drwtsn32x, any thoughts about this?

**Comment by drwtsn32x** [comment]
I looked at that thread and don't see where `snapshot-policy=auto` itself causes notifications.  I thought the OP was talking about notifications due to locked files, which appears when snapshots aren't enabled.  But I admit I only skimmed the thread.

Intuitively I would think setting it to `auto` would not cause any issues, and could be a better way to go.  That being said, it won't help many people since the default install runs non-elevated anyway.

**Comment by ts678** [comment]
The [explanation](https://github.com/duplicati/duplicati/issues/2833#issuecomment-345243861) for why this isn't the default is in #2833 that this PR means to fix. I haven't found the event yet. Has anyone else?

> The reason it is "off" is that it will otherwise create log entries in Windows Event Log with "permission denied".

**Comment by warwickmm** [comment]
> I looked at that thread and don't see where snapshot-policy=auto itself causes notifications. I thought the OP was talking about notifications due to locked files, which appears when snapshots aren't enabled. But I admit I only skimmed the thread.

You're right, I think I misread the post.  Are windows notification events raised when we attempt to read a locked file?

**Comment by kenkendk** [comment]
IIRC, the errors are shown in the Windows Event Log.
These errors occur if the user does not have permission to create the snapshot, but `auto` mode will not log the error in the Duplicati log.

I personally don't think it is a good idea to set it to auto.
- It only works if the user has permission
- The hard part is setting it up to run with elevated permissions
- It is easy to change the setting
- Snapshots are fairly invasive, with a few caveats of their own

A better approach would be to query if the current user has sufficient permissions, and if that is the case set the default to `On` (I dislike `auto` in general because you either want VSS or not, toggling without error messages is likely to cause issues down the line).

**Comment by warwickmm** [comment]
That makes sense to me.  Thanks @samuel-w for the proposed fix, but I agree with @kenkendk that we should consider a different approach for this.

**Pull request closed without merging**
