### PR TITLE
Recovery recompress

### PR DESCRIPTION
**Pull request by mnaiman**
Adds ability to recompress to another type (eg 7z->zip) whole remote backend.

### CODE REVIEW

**Comment by kenkendk** [comment]
Hi.

You need to add the "Recompress.cs" file to the .csproj file, otherwise it will not compile.

**Comment by mnaiman** [comment]
Youre right, Im new to Git from SVN and little bit fighting with commits.

**Comment by kenkendk** [comment]
Feel free to submit a new PR with your name added to the `acknowledgements.txt` file:
https://github.com/duplicati/duplicati/blob/master/Duplicati/License/acknowledgements.txt

**Comment by kenkendk** [comment]
And thanks for the work, it looks very nice.

**Pull request merged**
