### PR TITLE
Spelling fix loose to lose

### PR DESCRIPTION
**Pull request by davegold24**

### CODE REVIEW

**Comment by dgold9670** [comment]
@kenkendk what do I do with this one, where a check failed?

**Comment by davegold24** [comment]
@kenkendk what do I do with pull requests that fail the check?
also, was I correct to assign this to you, so you could verify and merge it?

**Comment by kenkendk** [comment]
@davegold24 The travis test occasionally fails (network errors, etc). I usually press the "re-run" button manually, but I don't think you can do anything.

**Comment by davegold24** [comment]
OK, let me know if you need me/want me to do anything. Like you said, I don't see rerun button.

**Comment by kenkendk** [comment]
Closing because I will make the update in a combined commit.

**Pull request closed without merging**
