### PR TITLE
Windows symlink restore problems

### PR DESCRIPTION
**Pull request by snamds**
- Fix. Alphaleonis.Win32.Filesystem.File.CreateSymbolicLink wrong parameters order. !?!?!?!?
- Fix. Relative target links didn't work
- Fix. Folder was created previous symlink creation

### CODE REVIEW

**Comment by snamds** [comment]
I was evaluating this software to use it and found that symlink restore doesn't work in windows.

· The Alphaleonis.Win32.Filesystem.File.CreateSymbolicLink parameters order was incorrect.
· The target passed to CreateSymbolicLink doesn't support relative paths. If you use relative paths, they are created using the execution path as reference. I've used the Path.Combine function to make it absolute.
· The code created an empty folder before evaluating the metadata info. When the metadada was evaluated, the symlink could not be created because the folder already existed.

**Comment by snamds** [comment]
There was a conflict with last changes in RestoreHandler.cs. Now it's ok.

**Comment by kenkendk** [comment]
Suppose you have this structure:
```
C:\a\
C:\a\b\
C:\a\d\
C:\a\b\c.txt
C:\a\d\f.txt
```

If you restore `*.txt`, you need to ensure that `C:\a\b\` and `C:\a\d\` are created, otherwise you will not be able to create the files `C:\a\b\c.txt` and `C:\a\d\f.txt`. The code you removed is making sure this happens.

Even if `C:\a\b\c.txt` is a symlink, you still need to create `C:\a\b\` and that will not interfere with creating the symlink. Are you seeing something else?

**Comment by snamds** [comment]
Ok @kenkendk , now I understand what you meant with "Is it another problem that it recreates the symlink folder and not the parent because the path ends with a backslash?"
Yes that was the problem. I've changed the "m_systemIO.PathGetDirectoryName" with "Duplicati.Library.Utility.Utility.GetParent"

**Comment by snamds** [comment]
I think https://github.com/duplicati/duplicati/issues/2640 will be fixed with this pr

**Pull request merged**
