### PR TITLE
On Azure backend, allow use of SAS token

### PR DESCRIPTION
**Pull request by sergethedev17**
1. Fixes a bug in AzureBlobBackend constructor.
2. Adds a feature to allow users to authenticate with Azure Storage using a Shared access signature (SAS) token. SAS tokens are more secure because they:
 * have a start and expiry date/time
 * can be restricted to specified IP addresses
 * can limit access scope to a single Storage blob container

SAS tokens can still be cancelled/revoked by changing/rotating the storage account Access Key.
This feature adds a new parameter named `azure-access-sas-token`, which can be used instead of `azure-access-key`. When both parameters are specified, the `azure-access-sas-token` parameter takes precedence.

More info about SAS tokens @ [Grant limited access to Azure Storage resources using shared access signatures (SAS)](https://docs.microsoft.com/en-us/azure/storage/common/storage-sas-overview).

Screenshot from Azure showing how to generate a SAS token:
2021-05-15 21_29_36-Window

### CODE REVIEW

**Comment by sergethedev17** [comment]
Don't know why macos tests failed. I think there may be an issue with the unit test.

**Comment by warwickmm** [comment]
> 1. Fixes a bug in AzureBlobBackend constructor.

Thanks for noticing this :+1: .  I created a separate pull request (see #4513) to fix the handling of the deprecated options to make it easier to quickly create an updated beta release if necessary.

**Comment by warwickmm** [comment]
> Don't know why macos tests failed. I think there may be an issue with the unit test.

Yes, there's an issue with the tests (or perhaps actual code) on macos that we haven't figured out yet.

**Comment by sergethedev17** [comment]
> 
> 
> > 1. Fixes a bug in AzureBlobBackend constructor.
> 
> Thanks for noticing this 👍 . I created a separate pull request (see #4513) to fix the handling of the deprecated options to make it easier to quickly create an updated beta release if necessary.

Thanks @warwickmm . I didn't know about those aws deprecated options. Also, your logic (`if`-`if`, instead of `if`-`else if`) is probably better.
What do you want to do with this PR?

**Comment by sergethedev17** [comment]
Question about testing connectivity.
In the `Duplicati.Library.Backend.AzureBlob.AzureBlobBackend` class, the `Test()` method simply enumerates all objects. There are 2 issues with this:

1. The backend may contain 100s (or 1000s?) of files. Enumerating all files is not necessary and can take a lot of time. Some cloud-based remotes charge users per API request.
2. The implementation does not test write functionality. With SAS tokens in particular, it is possible that enumeration is allowed, but writing or deleting blobs is not. (There was a similar issue with FTP; https://github.com/duplicati/duplicati/pull/2500).

Can I have a suggestion to improve the `Test()` method? Perhaps, enumerate first 10 files, create a test file (random name), write 1KB, read the file, delete the file.

**Comment by warwickmm** [comment]
> What do you want to do with this PR?

After pull request #4513 is merged, we can then merge the upstream branch into this one and resolve any conflicts.

> Can I have a suggestion to improve the Test() method? Perhaps, enumerate first 10 files, create a test file (random name), write 1KB, read the file, delete the file.

I think that's a good idea.  However, we should make such changes in a separate pull request since they are unrelated to this one.  The [AlternativeFTPBackend](https://github.com/duplicati/duplicati/blob/0a43410535d89e3e8ca93e78f799b9cec8812310/Duplicati/Library/Backend/AlternativeFTP/AlternativeFTPBackend.cs#L460) and [Tardigrade](https://github.com/duplicati/duplicati/blob/0a43410535d89e3e8ca93e78f799b9cec8812310/Duplicati/Library/Backend/Tardigrade/TardigradeBackend.cs#L297) backends have tests that do more than a simple list if you want to see existing examples.

**Comment by kenkendk** [comment]
I merged the commandline option fixes. Once the tests passes for this, I think it is good to merge.
(And yes, the `Test()` issue should go in another PR)

**Comment by warwickmm** [comment]
This looks good to me.  Thanks @sergethedev17 for this, and for noticing the bug in the `AzureBlobBackend` constructor.

**Pull request merged**
