### PR TITLE
Fix a word puzzle on localdatabase.html

### PR DESCRIPTION
**Pull request by luixxiul**
This PR intends to fix a word puzzle on localdatabase.html.

For "word puzzle", please see: https://techbase.kde.org/Development/Tutorials/Localization/i18n_Mistakes#Pitfall_#2:_Word_Puzzles.

Signed-off-by: Suguru Hirahara <luixxiul@users.noreply.github.com>

### CODE REVIEW

**Comment by luixxiul** [comment]
I am not perfectly sure if this works as expected; please feel free to fix it if it is not a right solution.

**Comment by luixxiul** [comment]
> Not sure the translation works correctly when there are html tags inside the translated string?

It should work fine. Here is an example:

https://github.com/duplicati/duplicati/blob/f444382e5f6c4d730bbe433cfe6cde02e2c96fcb/Duplicati/Server/webroot/ngax/templates/about.html#L12-L24

And the translation was properly handled:




HTML tags are apparently converted into placeholders on Transifex, and re-converted into HTML tags for PO files.

https://github.com/duplicati/duplicati/blob/f444382e5f6c4d730bbe433cfe6cde02e2c96fcb/Localizations/webroot/localization_webroot.pot#L3372-L3374

I do not see the reason why <b> tag would not be converted into a placeholder, so it should work fine...

**Comment by kenkendk** [comment]
Yeah, you are right, if it works in that instance, it will also work for `<b>`

**Comment by luixxiul** [comment]
Let's just revert the PR if it was found it indeed did not work :+1:

**Pull request merged**
