### PR TITLE
Fix for issue1400

### PR DESCRIPTION
**Pull request by BlueBlock**
There can essentially be a race between a file getting updated and Duplicati trying to back that file up. 

We'll use a 'limit' stream to limit the file streams length to be for that point in time.

As an aside, if Duplicati is processing slower than a file is being updated then a Duplicati backup will never end. We always want to be backing up a file of known length at that moment in time.

### CODE REVIEW

**Comment by warwickmm** [comment]
The test passed in AppVeyor, but failed in Travis.  It fails on my Linux machine as well, but I wasn't able to spend much time looking at it...

**Comment by BlueBlock** [comment]
Fixed the shared file access for the unittest. Though it looks like Travis is having some issues pulling build files.

**Comment by BlueBlock** [comment]
The unittest passes on Windows and Linux now.

**Comment by BlueBlock** [comment]
Are we to do a small commit to force new CI runs if they fail for non-code reasons?

**Comment by warwickmm** [comment]
I kicked off a re-build of the failed Travis jobs.

**Comment by BlueBlock** [comment]
Thanks

**Comment by warwickmm** [comment]
Nice job @ts678 and @BlueBlock.

**Comment by BlueBlock** [comment]
Thanks!

**Comment by ts678** [comment]
Thanks to all. I'm not sure if this is a 100% fix for all changing file scenarios, but it should help a LOT. Even better is that it finally made it into master (I wasn't expecting it would take 4 days...) so that will resolve the issue of whether or not to wait for it before turning master into canary, if that's our plan.

**Comment by drwtsn32x** [comment]
Nice work on this one!

**Pull request merged**
