### PR TITLE
Add back properties required by RUMPS (Mac status bar)

### PR DESCRIPTION
**Pull request by warwickmm**
These properties were removed in pull request #3534 when replacing write-only properties with methods.  While the properties were not being read in C#, there is Python code that depends on their availability.

This addresses issue #3550.

### CODE REVIEW

**Comment by Pectojin** [comment]
Just for ease of test/confirmation:

1. checkout Duplicati master branch on MacOS
2. build and run TrayIcon in Visual Studio
3. Keep an eye on Activity Monitor and console output, after a few moments a mono child process `Python` will spike in memory and CPU usage and it will generate huge amounts of logs.
4. shut it down. You may have to force quit the Python process as it seems to go zombie.
5. checkout the debug/rumps_runner branch
6. build and run
7. repeat. The console output will be as usual and the python child process will use virtually no resources.

**Comment by warwickmm** [comment]
Sorry about this.  I seem to be breaking a few things recently.

**Comment by Pectojin** [comment]
That's what we have canaries for :)
I don't think there was any way to know this was going to break from the changes made, it wasn't even obvious after it broke.

**Comment by kenkendk** [comment]
> Sorry about this. I seem to be breaking a few things recently.

No worries. Stuff breaks when you change things. I prefer the changes over stand-still :)

**Pull request merged**
