### PR TITLE
added repair button to the 'please repair' notification

### LINKED ISSUE #2118: "Please run repair" - how do I do that?
I have:
- [X] searched open and closed issues for duplicates

----------------------------------------

### Version info

**Duplicati Version:** 2.0.1.30_experimental_2016-11-03
**Operating System:** Win10
**Backend:** AWS S3

### Bug description
```
Error while running <MyBackup>
Found 1 remote files that are not recorded in local storage, please run repair
```

I couldn't find out what I should do..

### PR DESCRIPTION
**Pull request by Pectojin**
As discussed in https://forum.duplicati.com/t/how-to-please-run-repair/2771 it's not very obvious how to repair the database to new users. 

I Added a button to make it easy.
screen shot 2018-03-09 at 20 14 46

This also resolves #2118

### CODE REVIEW

**Comment by kenkendk** [comment]
With the new logging stuff I added, we can remove the dependency on the string (as it may be localized).

There is now a `MessageID` on the notification, and we should show the button for both `ExtraRemoteFiles` and `MissingRemoteFiles`.

I am merging anyway, because it still works and adds value for users.

**Comment by Pectojin** [comment]
Sounds good. We'll need to go through all the buttons anyway since a couple of them use text matching as well.

As usual I just stole some code and refactored it for this use-case.

**Comment by Pectojin** [comment]
@veleek I'm assuming this is on the beta version? 

The code is in the canary build since version 2.0.3.2 but the only beta released since then was 2.0.3.3 which was released shortly after so the fix didn't make it into that release.

**Comment by veleek** [comment]
Correct, the beta version.  There was some confusion on the other feature request thread so I thought I'd bring it up.  I'll follow up on the original issue.  Thanks!

**Pull request merged**
