### PR TITLE
Fixed multiple issues regarding listing folders and drives

### PR DESCRIPTION
**Pull request by mylemans**
Fixed: Listing drives on Windows now work if you have 1 or more drives that are 'not ready' or when a drive' details could not be retrieved while building the list (such entries are simply ignored)
Fixed: Trying to 'expand' a folder using the picker that became unavailable in the meanwhile will now properly show a client side error (instead of silently fail)

### CODE REVIEW

**Comment by mylemans** [comment]
Sorry about some of the whitespace related changes, it is my IDE doing that.

Also, note that I can only work with method based Linq queries, that is why I had to change it as such (the GetDrives Linq bit).

**Comment by mylemans** [comment]
Ugh I should not have done the pull request from my master.. I suck at github :s

Please review asap if possible, I have another pull request pending once I fix my repo again...

**Comment by kenkendk** [comment]
It is fine with the merged refs, I can still see the changes only.

Good fix, I will merge it now.

If you would like to be mentioned in the acknowledgements section, feel free to create a new pull request with a change to `License/acknowledgements.txt`.

**Comment by mylemans** [comment]
@kenkendk Maybe later, but can I contact you somewhere regarding a security issue I found? I'm working on a potential fix as we speak, but imho.. it something stupid but it is a security issue :s

**Comment by kenkendk** [comment]
Sure, you can drop me a mail: kenneth@duplicati.com

**Comment by bobambrosius** [comment]
I see now that the issue "Cannot list any files or folders in backup to and source data pickers #1662" is closed. Therefor my question again, here.
I have the data pickers problem in v2.0.1.18 on WIndows 10 using Edge on laptop (a). On another laptop (b) I have v2.01.1.16 running and there is no problem listing folders in the source data pickers, also WIndows 10 using Edge. However it is strange that, on laptop (a) after removing v2.0.1.18 and installing v2.0.1.16 I still have the folder pickers problem. How can it be that the same version behaves different on another computer?

**Comment by arghoyle** [comment]
@bobambrosius you can delete the %AppData%\Duplicati folder after uninstalling and then re-install the old version. Can verify that v2.0.1.16 is working and v2.0.1.18 is not expanding the selection folders on Win10 Ent x64.

**Comment by bobambrosius** [comment]
**@arghoyle** I tried that already. And now again on your advice. Regret to say it doesn;t work. Here's the situation on both my laptops(!): v2.0.1.16 win x64 worked fine. Updated to v2.0.1.18, and data pickers stopped working. Uninstalled, deleting %appdata%\Duplicati\, restarted computer (maybe redundant action), installed v2.0.1.16. Data pickers still not working!  So now I'm not backing up in the cloud, and cannot reach the backups that exist. After using it some months I judged Duplicati an awesome product, I hope you can restore my confidence.

**Comment by stanimirivanovde** [comment]
I'd like to mention that even after deleting %appdata%/Local/Duplicati and %appdata%/Roaming/Duplicati, and then running the 2.0.1.16 version, it still says in the About page: "You are currently running Duplicati - 2.0.1.18_canary_2016-08-10"

I am not sure how we can uninstall 2.0.1.18 cleanly. May be after a clean uninstall the old version 2.0.1.16 will work as it used to? If so can you please provide instructions on how to uninstall 2.0.1.18 properly? At least it will be a workaround for the problem.

**Comment by kenkendk** [comment]
Duplicati can store updates in a number of places, depending on what is write-able on your system.
You can run the executable in a console/commandline window:
```
Duplicati.Library.AutoUpdater.exe
```

And it will show near the end `Updates are installed in: ` and then the path where it has picked up the updates.

Remove that folder and you have uninstalled Duplicati updates.

**Comment by stanimirivanovde** [comment]
This was helpful and it showed the update location! Unfortunately I wasn't able to run 2.0.1.16. This is what I tried to do:
* I did a fresh download of 2.0.1.15 - 18 in the zip format
* I extracted all of them in separate directories
* I stopped 2.0.1.18 instance
* I tried starting 2.0.1.15 but it crashes and doesn't want to run
* 2.0.1.16 and 2.0.1.17 don't run at all. They don't crash but they never finish loading.
* Only 2.0.1.18 starts, but that one doesn't see the source folders so it is useless.

Could this be due to some windows update? Who knows, but latest Duplicati 2.0.1.18 can't list the local filesystem and that makes it pretty broken. How can I file a critical defect?

**Comment by kenkendk** [comment]
@stanimirivanovde: I fixed the issue with 2.0.1.20.
The crashes you report could be caused by 2.0.1.18 upgrading the settings database, which means you have to revert to the previous database to start (there should be a copy in the AppData folder).

**Comment by stanimirivanovde** [comment]
@kenkendk, thanks for addressing this! After having 2.0.1.20 installed everything works correctly.

**Comment by bobambrosius** [comment]
Great! Thanks for the swift action.

**Pull request merged**
