### PR TITLE
Added option to show sources for jobs on Home page

### PR DESCRIPTION
**Pull request by Pegoth**
Added the possibility to show sources on the Home page to be able to find a specific job easier.

image
image

### CODE REVIEW

**Comment by gpatel-fr** [comment]
Thanks for your contribution !
About the UI, the fact that the option in the User interface settings is above the language and color settings is hardly justified. My feeling is that these last 2 settings are more important. So it could be below these 2 settings.

I'd even tend to think that this change does not justify making the UI settings heavier and that this enhancement could just be the new behaviour (that is, without any parameter to enable/disable it: Duplicati already has a gazillion options, far too much in my opinion...)
If anyone is really using the UI to automate Duplicati so that their solution would be broken by the new UI, anyone is just wrong, the Python project is an example to do it right.

Thoughts (@ts678, @Jojo-1000, ... or anyone interested) ?

**Comment by Jojo-1000** [comment]
> this enhancement could just be the new behaviour

I wanted to ask: Was there a specific motivation for this change?

From my point of view, the benefit of this is not that big. You already have the description field if you want to add more info about the backup. In my main backup, this source list is about 20 entries long. They also don't give a full picture about the contents, because filters still need to be looked up on the edit page.

I don't mind it as a visual option, but if it is always on I would expect a scroll area so that the statistics are not obscured when it is visible. However, @gpatel-fr is right that the number of options should not needlessly be increased.

**Comment by ts678** [comment]
Basically, ditto, but I'll post anyway. I didn't yet get a chance to write the part about the filters also controlling the backup...

> to be able to find a specific job easier.

Wouldn't showing the optional Description be a more concise way to do that? For example, show it under Name on expand.
The example here only has 2 lines, but my rather small backup has 27. I could see someone having more than screen can fit.
Likely the end just drops off the screen end, but it should be tested. A long list will also mean people may want to unexpand
rather than just leaving job expanded. We've got some requests to be able to rearrange jobs order. This could increase need.

**Comment by Pegoth** [comment]
The motivation was just that I wanted to see the exact sources for each job, nothing fancy.

Description did not show new lines properly, so it was not an option for me to create a list there, therefore I made this PR.

I placed the setting under UI, because it is relevant to the user interface, but I'm fine removing it from there and just placing it under advanced or something.

**Comment by gpatel-fr** [comment]
>>Description did not show new lines properly
yes and that's not pretty (even if it's concise but when it's forced by software that's not a quality IMO)

I have tested this solution https://stackoverflow.com/questions/19684708/preserve-line-breaks-in-angularjs and it works but it has the drawback of adding 2 useless line feeds before the description.

To get back to your proposal, it could be changed easily by moving the ng-repeat="source in item.Backup.Sources">{{source}} thingy under the description field in the home.html template, then add an extended option named show-sources-in-job-description (just an idea, you can name it otherwise if it makes more sense) that could be added in the settings page, that would avoids making the settings page more heavy for an option that is not felt useful by everyone  (my original reservation).
so:
@Pegoth : could this change be easy enough for you ? you can add an extended option to Duplicati in Main/Options.cs and Main/Strings.cs, see an example in https://github.com/duplicati/duplicati/commit/68c36edbf7307f632aff41fec25d53f3edadc5db#diff-f2f3de51cabef256347ac28378ca3913bcfd30688540668a711b4029fab6fe6cR423 , and you can test for it in a template code with the Options['name-of-option'] syntax I think. Ideally the change could be made simpler, even if it means adding the sources to each backup regardless of the option (the load is not significant IMO).

@ts678 and @Jojo-1000: could it be more acceptable for you ?

**Comment by Pegoth** [comment]
I would prefer if the UI of the job would be like what I did. The place where the config is doesn't really matter for me as I'll just set it to enabled once and done.

**Comment by gpatel-fr** [comment]
sooooooo: @ts678  and @Jojo-1000 : would the same patch but with an extended option instead of the UI option be acceptable for you ?

**Comment by Jojo-1000** [comment]
> you can add an extended option to Duplicati in Main/Options.cs

The issue is that this will show up in all extended options and also CLI help texts. I would prefer not to have any options that have no relevance to CLI in the backup settings. I think the Server UI settings is the right place for this, maybe below the theme.

> I would prefer if the UI of the job would be like what I did.

*If* there is a setting to show the source list, I think it should have its own section.

@Pegoth Can you try to add `white-space: pre-line` to the description field and see if it would be an acceptable compromise? I think it would be positive change either way. This will keep line breaks in the description, but remove extra whitespace and break too long lines.

In my opinion, the way this change is currently done is not bad. The only question is, do enough people need this to justify the added option. Given that at least @Pegoth wanted it bad enough to do the work, I would argue why not. Since this is only a server setting, we could also remove it in the future, if we decide it is not useful.

**Comment by gpatel-fr** [comment]
>>I would prefer not to have any options that have no relevance to CLI in the backup settings

that's your preference. I don't see why there should be a rule forbidding having a job setting impacting the UI, and making this choice an extended setting would also turn it into a job setting (per-job configurable). The Settings page is a page for Server settings, not especially UI settings.

>>Can you try to add white-space: pre-line to the description field and see if it would be an acceptable compromise?

not for me.
Screenshot_20231210_141501

The extra white line before the description would be a regression. And asking for fixing this particular problem without having any idea of the complexity seems unfair. It could be easy or it could turn around to be a monster of a hellish problem involving different browsers implementations or standard conflicts or whatever.

**Comment by Jojo-1000** [comment]
You might have it at the wrong element:

```html
<span ng-show="item.Backup.Description">
    <dt translate>Description:</dt>
    <dd style="white-space: pre-line;">{{item.Backup.Description}}</dd>
</span>
```
If the `dd` tag has the content on one line without whitespace, it is also possible to have the user completely control whitespace:

Before:
description before change

With `pre-line`:
description with pre-line whitespace

With `pre-wrap`:
description with pre-wrap whitespace



The CSS seems to be [supported since 2009-2013 in all major browsers](https://developer.mozilla.org/en-US/docs/Web/CSS/white-space#browser_compatibility)

**Comment by gpatel-fr** [comment]
At the moment I'm unable to repro this. With pre-line the superflous white line still displays. With pre-wrap it's worse:

image

**Comment by ts678** [comment]
I'm surprised it's so hard to put text in a box, but I don't code GUI. Ideally, any method would be portable beyond AngularJS. 
Would browser web developer tools be able to see what's on the page, maybe to give some clue if things aren't looking nice?

If we return to the source list plan, first I'll note that there's a request to sort it, instead of displaying it in original entry order, however a tempting (though I don't know what code or HTML magic it needs) path to source details is to click on Source line.
We're doing something like that on lines in About --> Show log

**Comment by gpatel-fr** [comment]
>>You might have it at the wrong

oh yes, I started on a wrong hypothesis all right, now it's working.
Given that, I'd say that this PR is not needed after all, fixing this problem in the Description display allow to solve it without adding any specific code. Do you want to do a PR for that ?

**Comment by gpatel-fr** [comment]
@Pegoth 
thanks again for the effort, as the idea did not agree with everyone, it appears that the better solution is to fix the description field bug, something I merged just now into Duplicati. I agree that it needs more manual work especially when the sources change, but on the other hand I also prefer not to load the UI with non essential features.

**Pull request closed without merging**
