### PR TITLE
New improvements on Backup Logs UI

### PR DESCRIPTION
**Pull request by mikaelmello**
This PR also includes a fix for things that I changed and broke IE compatibility.

### CODE REVIEW

**Comment by mikaelmello** [comment]
Also, unrelated question: why are the releases not being version bumped on master anymore?

**Comment by mikaelmello** [comment]
Even if approved, don't merge this yet. I'm improving a few things

**Comment by Pectojin** [comment]
I think you might have based this on the wrong branch. It's including 400k line changes from a bunch of translations and it adds release notes from the canary branch.

Can you rebase your changes off main?

**Comment by warwickmm** [comment]
> Also, unrelated question: why are the releases not being version bumped on master anymore?

Yes, I can't find revision 8ffff6f90674386d8d4eda7defad1c4413d1612d, which is the version bump, or a tag for version v2.0.4.6.

**Comment by mikaelmello** [comment]
> I think you might have based this on the wrong branch.

I've based it on the latest canary release. Hence why I'm asking why it isn't on master

> Was the lack of a version bump in master just an oversight?

Exactly my thought, but this also happened on latest beta. Is it intended behavior or kenkendk let it pass accidentally?

**Comment by kenkendk** [comment]
I reviewed the changes locally, and I am fine with merging and getting a new canary out.

**Pull request merged**
