### PR TITLE
Fix quota parm desc. typo

### PR DESCRIPTION
**Pull request by JonMikelV**
Simple typo fix in UI description of quota-warning-threshold parameter.

### CODE REVIEW

**Comment by JonMikelV** [comment]
Are there supposed to be 3 commits (2 of which are just updating my master with THE master) or did I do something in a less-than-optimal way?  :-)

**Comment by warwickmm** [comment]
It looks like the `master` branch in your fork was a bit behind the `master` branch in this repository.  Other than the logs being a bit cluttered, the end result is fine.  Would you be open to trying to cherry-pick this commit (e3ba023b5) onto a branch based on the upstream `master`?

**Comment by Pectojin** [comment]
I don't think there's a Github UI way of doing cherry picks, requires the git CLI or another external tool. 

I'm ok with merging it like this, though.

**Comment by Pectojin** [comment]
Ah, look at that. I got to try something new. I squashed the commits into one when merging it: https://github.com/duplicati/duplicati/commit/fff5145e2f22dda12320493bad54030a17048473

So history looks good 👍

**Comment by JonMikelV** [comment]
If you're open to helping me learn how to do it, I'm open to trying it out. 
 :-)

**Comment by JonMikelV** [comment]
Oof.

 Reading through that reminds me I've got 10 years of SVN usage to unlearn 
before I actually start understanding what I'm doing in git rather than 
just typing that people tell me to.  :-)

**Pull request merged**
